# Generated by Django 4.2.11 on 2025-04-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='health_scores',
            field=models.JSONField(blank=True, help_text="Stores quantifiable health scores (e.g., {'gill_health': 1, 'eye_condition': 2}).", null=True),
        ),
    ]
