# Generated by Django 4.2.11 on 2025-04-14 14:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_container_feed_recommendations_enabled_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batch', '0001_initial'),
        ('health', '0002_journalentry_health_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the health parameter (e.g., Gill Health).', max_length=100, unique=True)),
                ('description_score_1', models.TextField(help_text='Description for score 1 (Good).')),
                ('description_score_2', models.TextField(help_text='Description for score 2.')),
                ('description_score_3', models.TextField(help_text='Description for score 3.')),
                ('description_score_4', models.TextField(help_text='Description for score 4 (Bad).')),
                ('is_active', models.BooleanField(default=True, help_text='Is this parameter currently in use?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='journalentry',
            name='health_scores',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='batch',
            field=models.ForeignKey(help_text='The batch associated with this journal entry.', on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='batch.batch'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='category',
            field=models.CharField(choices=[('observation', 'Observation'), ('issue', 'Issue'), ('action', 'Action'), ('diagnosis', 'Diagnosis'), ('treatment', 'Treatment'), ('vaccination', 'Vaccination'), ('sample', 'Sample')], max_length=20),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='container',
            field=models.ForeignKey(blank=True, help_text='The specific container, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='infrastructure.container'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='severity',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='user',
            field=models.ForeignKey(help_text='User who created the entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HealthObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score from 1 (Good) to 4 (Bad).', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_observations', to='health.journalentry')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='health.healthparameter')),
            ],
            options={
                'unique_together': {('journal_entry', 'parameter')},
            },
        ),
    ]
