# Generated by Django 4.2.11 on 2025-04-15 14:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0004_alter_journalentry_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="healthobservation",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="healthobservation",
            name="fish_identifier",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Identifier for individual fish within a sample (e.g., 1-75), if applicable.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="healthparameter",
            name="description_score_5",
            field=models.TextField(
                default="", help_text="Description for score 5 (Worst/Critical)."
            ),
        ),
        migrations.AlterField(
            model_name="healthobservation",
            name="score",
            field=models.IntegerField(
                help_text="Score from 1 (Best) to 5 (Worst).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="healthparameter",
            name="description_score_1",
            field=models.TextField(
                help_text="Description for score 1 (Best/Excellent)."
            ),
        ),
        migrations.AlterField(
            model_name="healthparameter",
            name="description_score_2",
            field=models.TextField(help_text="Description for score 2 (Good)."),
        ),
        migrations.AlterField(
            model_name="healthparameter",
            name="description_score_3",
            field=models.TextField(
                help_text="Description for score 3 (Fair/Moderate)."
            ),
        ),
        migrations.AlterField(
            model_name="healthparameter",
            name="description_score_4",
            field=models.TextField(help_text="Description for score 4 (Poor/Severe)."),
        ),
    ]
