# Generated by Django 4.2.11 on 2025-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_alter_healthobservation_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='sampling_event_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Shared identifier for associating growth and health data in sampling events.', null=True),
        ),
    ]
