# Generated by Django 4.2.11 on 2025-04-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_create_sampling_event_sequence'),
    ]

    operations = [
    ]
