# Generated by Django 4.2.11 on 2025-04-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_remove_journalentry_sampling_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='sampling_event_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Identifier linking journal entries and samples from the same sampling event', null=True),
        ),
    ]
