# Generated by Django 4.2.11 on 2025-04-30 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_journalentry_sampling_event_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='sampling_event_id',
        ),
    ]
