# Generated by Django 4.2.11 on 2025-04-30 10:52

from django.db import migrations
from django.conf import settings

# SQL to drop the sequence (PostgreSQL specific)
DROP_SEQUENCE_SQL = """
DROP SEQUENCE IF EXISTS sampling_event_id_seq;
"""

# SQL to create the sequence (PostgreSQL specific) - For reverse operation
CREATE_SEQUENCE_SQL = """
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE sequencename = 'sampling_event_id_seq') THEN
        CREATE SEQUENCE sampling_event_id_seq START 1 INCREMENT 1;
    END IF;
END $$;
"""

class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_remove_journalentry_sampling_event_id'),
    ]

    operations = [
        # Only run this operation if the database is PostgreSQL
        migrations.RunSQL(
            sql=DROP_SEQUENCE_SQL,
            reverse_sql=CREATE_SEQUENCE_SQL,
        ) if settings.DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql' else migrations.RunSQL.noop,
    ]
