# Generated by Django 4.2.11 on 2025-05-07 13:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0012_remove_growthsample_sampling_event_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0012_drop_sampling_event_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishParameterScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Score from 1 (Best) to 5 (Worst) for the health parameter.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fish Parameter Score',
                'verbose_name_plural': 'Fish Parameter Scores',
                'ordering': ['individual_fish_observation', 'parameter'],
            },
        ),
        migrations.CreateModel(
            name='HealthSamplingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampling_date', models.DateField(default=django.utils.timezone.now)),
                ('number_of_fish_sampled', models.PositiveIntegerField(help_text='Total number of individual fish examined in this sampling event.')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(help_text='The specific batch and container assignment being sampled.', on_delete=django.db.models.deletion.CASCADE, related_name='health_sampling_events', to='batch.batchcontainerassignment')),
                ('sampled_by', models.ForeignKey(blank=True, help_text='User who conducted the sampling.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_sampling_events_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Sampling Event',
                'verbose_name_plural': 'Health Sampling Events',
                'ordering': ['-sampling_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndividualFishObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish_identifier', models.PositiveIntegerField(help_text='Sequential identifier for the fish within this sampling event (e.g., 1, 2, 3...).')),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, help_text='Length of the fish in centimeters.', max_digits=5, null=True)),
                ('weight_g', models.DecimalField(blank=True, decimal_places=2, help_text='Weight of the fish in grams.', max_digits=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sampling_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_fish_observations', to='health.healthsamplingevent')),
            ],
            options={
                'verbose_name': 'Individual Fish Observation',
                'verbose_name_plural': 'Individual Fish Observations',
                'ordering': ['sampling_event', 'fish_identifier'],
                'unique_together': {('sampling_event', 'fish_identifier')},
            },
        ),
        migrations.AlterModelOptions(
            name='mortalityreason',
            options={'ordering': ['name'], 'verbose_name_plural': 'Mortality Reasons'},
        ),
        migrations.AlterModelOptions(
            name='vaccinationtype',
            options={'ordering': ['name'], 'verbose_name_plural': 'Vaccination Types'},
        ),
        migrations.DeleteModel(
            name='HealthObservation',
        ),
        migrations.AddField(
            model_name='fishparameterscore',
            name='individual_fish_observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_scores', to='health.individualfishobservation'),
        ),
        migrations.AddField(
            model_name='fishparameterscore',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fish_scores', to='health.healthparameter'),
        ),
        migrations.AlterUniqueTogether(
            name='fishparameterscore',
            unique_together={('individual_fish_observation', 'parameter')},
        ),
    ]
