# Generated by Django 4.2.11 on 2025-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_fishparameterscore_healthsamplingevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthsamplingevent',
            name='avg_k_factor',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated average K-factor for fish with both weight and length.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthsamplingevent',
            name='avg_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated average length of sampled fish in centimeters.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthsamplingevent',
            name='avg_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated average weight of sampled fish in grams.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='healthsamplingevent',
            name='calculated_sample_size',
            field=models.PositiveIntegerField(blank=True, help_text='Actual number of fish with weight measurements in this sample.', null=True),
        ),
        migrations.AddField(
            model_name='healthsamplingevent',
            name='max_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum length recorded in this sample.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthsamplingevent',
            name='max_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum weight recorded in this sample.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='healthsamplingevent',
            name='min_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum length recorded in this sample.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthsamplingevent',
            name='min_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum weight recorded in this sample.', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='healthsamplingevent',
            name='std_dev_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated standard deviation of length for sampled fish.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='healthsamplingevent',
            name='std_dev_weight_g',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated standard deviation of weight for sampled fish.', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='healthsamplingevent',
            name='number_of_fish_sampled',
            field=models.PositiveIntegerField(help_text='Target or initially declared number of individual fish to be examined in this sampling event.'),
        ),
    ]
