# Generated by Django 4.2.11 on 2025-05-09 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('batch', '0012_remove_growthsample_sampling_event_id_and_more'),
        ('health', '0014_healthsamplingevent_avg_k_factor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLabSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateField(help_text='Date the sample was physically taken. Crucial for historical linkage.')),
                ('date_sent_to_lab', models.DateField(blank=True, help_text='Date the sample was sent to the laboratory.', null=True)),
                ('date_results_received', models.DateField(blank=True, help_text='Date the results were received from the laboratory.', null=True)),
                ('lab_reference_id', models.CharField(blank=True, help_text='External reference ID from the laboratory.', max_length=100, null=True)),
                ('findings_summary', models.TextField(blank=True, help_text='Qualitative summary of the lab findings.', null=True)),
                ('quantitative_results', models.JSONField(blank=True, help_text="Structured quantitative results (e.g., {'param': 'value', 'unit': 'cfu/ml'}).", null=True)),
                ('attachment', models.FileField(blank=True, help_text='File attachment for the lab report (e.g., PDF).', null=True, upload_to='health/lab_samples/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments by the veterinarian.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_container_assignment', models.ForeignKey(help_text='The specific batch-container assignment active when the sample was taken.', on_delete=django.db.models.deletion.PROTECT, related_name='lab_samples', to='batch.batchcontainerassignment')),
                ('recorded_by', models.ForeignKey(blank=True, help_text='User who recorded this lab sample result.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_lab_samples', to=settings.AUTH_USER_MODEL)),
                ('sample_type', models.ForeignKey(help_text='Type of sample taken (e.g., skin mucus, water sample).', on_delete=django.db.models.deletion.PROTECT, related_name='lab_samples', to='health.sampletype')),
            ],
            options={
                'verbose_name': 'Health Lab Sample',
                'verbose_name_plural': 'Health Lab Samples',
                'ordering': ['-sample_date', '-created_at'],
            },
        ),
    ]
