# Generated by Django 4.2.11 on 2025-06-11 10:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0015_update_feedstock_timestamps"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("infrastructure", "0005_update_feedstock_timestamps"),
        ("health", "0016_fix_nullable_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishparameterscore",
            name="individual_fish_observation",
            field=models.ForeignKey(
                help_text="The individual fish observation this score belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parameter_scores",
                to="health.individualfishobservation",
            ),
        ),
        migrations.AlterField(
            model_name="fishparameterscore",
            name="parameter",
            field=models.ForeignKey(
                help_text="The health parameter being scored.",
                on_delete=django.db.models.deletion.PROTECT,
                to="health.healthparameter",
            ),
        ),
        migrations.AlterField(
            model_name="fishparameterscore",
            name="score",
            field=models.PositiveSmallIntegerField(
                help_text="Score from 1 (best) to 5 (worst).",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="healthsamplingevent",
            name="avg_k_factor",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                help_text="Average condition factor (K) of sampled fish.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthsamplingevent",
            name="avg_length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average length in centimeters of sampled fish.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthsamplingevent",
            name="avg_weight_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average weight in grams of sampled fish.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthsamplingevent",
            name="calculated_sample_size",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Actual number of fish with measurements in this sample.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthsamplingevent",
            name="max_length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum length in centimeters among sampled fish.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthsamplingevent",
            name="max_weight_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum weight in grams among sampled fish.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthsamplingevent",
            name="min_length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum length in centimeters among sampled fish.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthsamplingevent",
            name="min_weight_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum weight in grams among sampled fish.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthsamplingevent",
            name="std_dev_length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Standard deviation of length in centimeters.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="healthsamplingevent",
            name="std_dev_weight_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Standard deviation of weight in grams.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="individualfishobservation",
            name="fish_identifier",
            field=models.CharField(
                help_text="Identifier for the specific fish (e.g., tag number or sequential ID).",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="individualfishobservation",
            name="length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Length of the fish in centimeters.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="individualfishobservation",
            name="sampling_event",
            field=models.ForeignKey(
                help_text="The health sampling event this observation belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="individual_fish_observations",
                to="health.healthsamplingevent",
            ),
        ),
        migrations.AlterField(
            model_name="individualfishobservation",
            name="weight_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Weight of the fish in grams.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="adult_female_count",
            field=models.PositiveIntegerField(
                help_text="Number of adult female lice counted."
            ),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="adult_male_count",
            field=models.PositiveIntegerField(
                help_text="Number of adult male lice counted."
            ),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="batch",
            field=models.ForeignKey(
                help_text="The batch being counted.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lice_counts",
                to="batch.batch",
            ),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="container",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific container, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lice_counts",
                to="infrastructure.container",
            ),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="count_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="fish_sampled",
            field=models.PositiveIntegerField(
                help_text="Number of fish sampled for the count."
            ),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="juvenile_count",
            field=models.PositiveIntegerField(
                help_text="Number of juvenile lice counted."
            ),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the lice count."
            ),
        ),
        migrations.AlterField(
            model_name="mortalityrecord",
            name="batch",
            field=models.ForeignKey(
                help_text="The batch experiencing mortality.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mortality_records",
                to="batch.batch",
            ),
        ),
        migrations.AlterField(
            model_name="mortalityrecord",
            name="container",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific container, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mortality_records",
                to="infrastructure.container",
            ),
        ),
        migrations.AlterField(
            model_name="mortalityrecord",
            name="count",
            field=models.PositiveIntegerField(help_text="Number of fish that died."),
        ),
        migrations.AlterField(
            model_name="mortalityrecord",
            name="event_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="mortalityrecord",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the mortality event."
            ),
        ),
        migrations.AlterField(
            model_name="mortalityrecord",
            name="reason",
            field=models.ForeignKey(
                help_text="Reason for the mortality.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mortality_records",
                to="health.mortalityreason",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="batch",
            field=models.ForeignKey(
                help_text="The batch receiving the treatment.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatments",
                to="batch.batch",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="batch_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific batch-container assignment, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatments",
                to="batch.batchcontainerassignment",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="container",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific container, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="treatments",
                to="infrastructure.container",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="description",
            field=models.TextField(help_text="Description of the treatment."),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="dosage",
            field=models.CharField(
                blank=True,
                help_text="Dosage of medication or treatment.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="duration_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Duration of treatment in days."
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("successful", "Successful"),
                    ("partial", "Partially Successful"),
                    ("unsuccessful", "Unsuccessful"),
                ],
                default="pending",
                help_text="Outcome of the treatment.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="treatment_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="treatment_type",
            field=models.CharField(
                choices=[
                    ("medication", "Medication"),
                    ("vaccination", "Vaccination"),
                    ("physical", "Physical Treatment"),
                    ("other", "Other"),
                ],
                help_text="Type of treatment administered.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="user",
            field=models.ForeignKey(
                help_text="User who recorded the treatment.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treatments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="vaccination_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific vaccination type, if applicable.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="treatments",
                to="health.vaccinationtype",
            ),
        ),
        migrations.AlterField(
            model_name="treatment",
            name="withholding_period_days",
            field=models.PositiveIntegerField(
                default=0, help_text="Withholding period in days."
            ),
        ),
        migrations.AlterField(
            model_name="vaccinationtype",
            name="dosage",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
