# Generated by Django 4.2.11 on 2025-10-17 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("health", "0019_add_history_to_observation_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicallicecount",
            name="confidence_level",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Confidence level of the count (0.00-1.00), where 1.00 is highest confidence.",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallicecount",
            name="count_value",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Count for the specific lice type. Use with lice_type field.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicallicecount",
            name="detection_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("automated", "Automated Detection"),
                    ("manual", "Manual Visual Count"),
                    ("visual", "Visual Estimation"),
                    ("camera", "Camera-based Detection"),
                ],
                help_text="Method used to detect and count lice.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="licecount",
            name="confidence_level",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Confidence level of the count (0.00-1.00), where 1.00 is highest confidence.",
                max_digits=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="licecount",
            name="count_value",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Count for the specific lice type. Use with lice_type field.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="licecount",
            name="detection_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("automated", "Automated Detection"),
                    ("manual", "Manual Visual Count"),
                    ("visual", "Visual Estimation"),
                    ("camera", "Camera-based Detection"),
                ],
                help_text="Method used to detect and count lice.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicallicecount",
            name="adult_female_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="[LEGACY] Number of adult female lice counted. Use lice_type_counts for new data.",
            ),
        ),
        migrations.AlterField(
            model_name="historicallicecount",
            name="adult_male_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="[LEGACY] Number of adult male lice counted. Use lice_type_counts for new data.",
            ),
        ),
        migrations.AlterField(
            model_name="historicallicecount",
            name="juvenile_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="[LEGACY] Number of juvenile lice counted. Use lice_type_counts for new data.",
            ),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="adult_female_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="[LEGACY] Number of adult female lice counted. Use lice_type_counts for new data.",
            ),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="adult_male_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="[LEGACY] Number of adult male lice counted. Use lice_type_counts for new data.",
            ),
        ),
        migrations.AlterField(
            model_name="licecount",
            name="juvenile_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="[LEGACY] Number of juvenile lice counted. Use lice_type_counts for new data.",
            ),
        ),
        migrations.CreateModel(
            name="LiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        help_text="Scientific name of the lice species (e.g., Lepeophtheirus salmonis, Caligus elongatus).",
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Gender classification of the lice.",
                        max_length=20,
                    ),
                ),
                (
                    "development_stage",
                    models.CharField(
                        help_text="Development stage (e.g., copepodid, chalimus, pre-adult, adult).",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional description or notes about this lice type classification.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this lice type is currently tracked in the system.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lice Type",
                "verbose_name_plural": "Lice Types",
                "ordering": ["species", "development_stage", "gender"],
                "indexes": [
                    models.Index(
                        fields=["species", "development_stage"],
                        name="health_lice_species_6bb9eb_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="health_lice_is_acti_ae0e03_idx"
                    ),
                ],
                "unique_together": {("species", "gender", "development_stage")},
            },
        ),
        migrations.CreateModel(
            name="HistoricalLiceType",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        help_text="Scientific name of the lice species (e.g., Lepeophtheirus salmonis, Caligus elongatus).",
                        max_length=100,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="Gender classification of the lice.",
                        max_length=20,
                    ),
                ),
                (
                    "development_stage",
                    models.CharField(
                        help_text="Development stage (e.g., copepodid, chalimus, pre-adult, adult).",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Additional description or notes about this lice type classification.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this lice type is currently tracked in the system.",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Lice Type",
                "verbose_name_plural": "historical Lice Types",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="historicallicecount",
            name="lice_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Normalized lice type classification (species, gender, development stage).",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="health.licetype",
            ),
        ),
        migrations.AddField(
            model_name="licecount",
            name="lice_type",
            field=models.ForeignKey(
                blank=True,
                help_text="Normalized lice type classification (species, gender, development stage).",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lice_counts",
                to="health.licetype",
            ),
        ),
    ]
