# Generated by Django 4.2.11 on 2025-10-17 11:36

from django.db import migrations


def populate_lice_types(apps, schema_editor):
    """Populate the LiceType lookup table with standard lice classifications."""
    LiceType = apps.get_model('health', 'LiceType')
    
    # Define standard lice types based on common aquaculture practices
    # Primary species: Lepeophtheirus salmonis (salmon louse) - most common in salmon farming
    # Secondary species: Caligus elongatus - less harmful but monitored
    
    standard_types = [
        # Lepeophtheirus salmonis - Female lifecycle
        {
            'species': 'Lepeophtheirus salmonis',
            'gender': 'female',
            'development_stage': 'copepodid',
            'description': 'Free-swimming larval stage, infectious to fish'
        },
        {
            'species': 'Lepeophtheirus salmonis',
            'gender': 'female',
            'development_stage': 'chalimus',
            'description': 'Attached juvenile stage (chalimus I-IV)'
        },
        {
            'species': 'Lepeophtheirus salmonis',
            'gender': 'female',
            'development_stage': 'pre-adult',
            'description': 'Mobile pre-adult female, approaching reproductive maturity'
        },
        {
            'species': 'Lepeophtheirus salmonis',
            'gender': 'female',
            'development_stage': 'adult',
            'description': 'Gravid (egg-bearing) adult female - regulatory focus'
        },
        
        # Lepeophtheirus salmonis - Male lifecycle
        {
            'species': 'Lepeophtheirus salmonis',
            'gender': 'male',
            'development_stage': 'copepodid',
            'description': 'Free-swimming larval stage, infectious to fish'
        },
        {
            'species': 'Lepeophtheirus salmonis',
            'gender': 'male',
            'development_stage': 'chalimus',
            'description': 'Attached juvenile stage (chalimus I-IV)'
        },
        {
            'species': 'Lepeophtheirus salmonis',
            'gender': 'male',
            'development_stage': 'pre-adult',
            'description': 'Mobile pre-adult male'
        },
        {
            'species': 'Lepeophtheirus salmonis',
            'gender': 'male',
            'development_stage': 'adult',
            'description': 'Adult male louse'
        },
        
        # Caligus elongatus - Female lifecycle (less detailed tracking typically)
        {
            'species': 'Caligus elongatus',
            'gender': 'female',
            'development_stage': 'juvenile',
            'description': 'Juvenile Caligus (combined early stages)'
        },
        {
            'species': 'Caligus elongatus',
            'gender': 'female',
            'development_stage': 'adult',
            'description': 'Adult female Caligus'
        },
        
        # Caligus elongatus - Male lifecycle
        {
            'species': 'Caligus elongatus',
            'gender': 'male',
            'development_stage': 'juvenile',
            'description': 'Juvenile Caligus (combined early stages)'
        },
        {
            'species': 'Caligus elongatus',
            'gender': 'male',
            'development_stage': 'adult',
            'description': 'Adult male Caligus'
        },
        
        # Unknown species (for legacy data migration or uncertain identifications)
        {
            'species': 'Unknown',
            'gender': 'unknown',
            'development_stage': 'juvenile',
            'description': 'Unidentified juvenile lice'
        },
        {
            'species': 'Unknown',
            'gender': 'female',
            'development_stage': 'adult',
            'description': 'Adult female lice - species unidentified'
        },
        {
            'species': 'Unknown',
            'gender': 'male',
            'development_stage': 'adult',
            'description': 'Adult male lice - species unidentified'
        },
    ]
    
    # Bulk create all lice types
    lice_types = [LiceType(**lice_type_data) for lice_type_data in standard_types]
    LiceType.objects.bulk_create(lice_types, ignore_conflicts=True)


def reverse_populate_lice_types(apps, schema_editor):
    """Remove all lice types created by the populate operation."""
    LiceType = apps.get_model('health', 'LiceType')
    LiceType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0020_add_lice_type_model"),
    ]

    operations = [
        migrations.RunPython(populate_lice_types, reverse_populate_lice_types),
    ]
