# Generated by Django 4.2.11 on 2025-10-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0023_create_initial_health_parameters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthparameter",
            name="description_score_1",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[DEPRECATED] Description for score 1. Use score_definitions instead.",
            ),
        ),
        migrations.AlterField(
            model_name="healthparameter",
            name="description_score_2",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[DEPRECATED] Description for score 2. Use score_definitions instead.",
            ),
        ),
        migrations.AlterField(
            model_name="healthparameter",
            name="description_score_3",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[DEPRECATED] Description for score 3. Use score_definitions instead.",
            ),
        ),
        migrations.AlterField(
            model_name="healthparameter",
            name="description_score_4",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[DEPRECATED] Description for score 4. Use score_definitions instead.",
            ),
        ),
        migrations.AlterField(
            model_name="healthparameter",
            name="description_score_5",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[DEPRECATED] Description for score 5. Use score_definitions instead.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealthparameter",
            name="description_score_1",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[DEPRECATED] Description for score 1. Use score_definitions instead.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealthparameter",
            name="description_score_2",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[DEPRECATED] Description for score 2. Use score_definitions instead.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealthparameter",
            name="description_score_3",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[DEPRECATED] Description for score 3. Use score_definitions instead.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealthparameter",
            name="description_score_4",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[DEPRECATED] Description for score 4. Use score_definitions instead.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealthparameter",
            name="description_score_5",
            field=models.TextField(
                blank=True,
                default="",
                help_text="[DEPRECATED] Description for score 5. Use score_definitions instead.",
            ),
        ),
    ]
