# Generated by Django 4.2.11 on 2025-10-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0024_make_legacy_fields_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthparameter",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="General description of this health parameter",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalhealthparameter",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="General description of this health parameter",
                null=True,
            ),
        ),
    ]
