# Generated by Django 4.2.11 on 2025-10-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0025_make_description_nullable"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="healthparameter",
            name="description_score_1",
        ),
        migrations.RemoveField(
            model_name="healthparameter",
            name="description_score_2",
        ),
        migrations.RemoveField(
            model_name="healthparameter",
            name="description_score_3",
        ),
        migrations.RemoveField(
            model_name="healthparameter",
            name="description_score_4",
        ),
        migrations.RemoveField(
            model_name="healthparameter",
            name="description_score_5",
        ),
        migrations.RemoveField(
            model_name="historicalhealthparameter",
            name="description_score_1",
        ),
        migrations.RemoveField(
            model_name="historicalhealthparameter",
            name="description_score_2",
        ),
        migrations.RemoveField(
            model_name="historicalhealthparameter",
            name="description_score_3",
        ),
        migrations.RemoveField(
            model_name="historicalhealthparameter",
            name="description_score_4",
        ),
        migrations.RemoveField(
            model_name="historicalhealthparameter",
            name="description_score_5",
        ),
    ]
