# Generated by Django 4.2.11 on 2025-11-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0037_add_assignment_to_mortality_event"),
        ("health", "0028_add_assignment_to_lice_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmortalityrecord",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Container-specific assignment where mortality occurred",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="batch.batchcontainerassignment",
            ),
        ),
        migrations.AddField(
            model_name="mortalityrecord",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Container-specific assignment where mortality occurred",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mortality_records",
                to="batch.batchcontainerassignment",
            ),
        ),
    ]
