# Generated by Django 4.2.11 on 2026-01-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0029_add_assignment_to_mortality_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortalityreason",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent mortality reason for hierarchical grouping",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="health.mortalityreason",
            ),
        ),
    ]
# Generated by Django 4.2.11 on 2026-01-20 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("health", "0029_add_assignment_to_mortality_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="mortalityreason",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent mortality reason for hierarchical grouping",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="health.mortalityreason",
            ),
        ),
    ]
