# Generated by Django 4.2.11 on 2025-11-24 15:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "infrastructure",
            "0008_alter_area_options_alter_containertype_options_and_more",
        ),
        ("environmental", "0014_create_daily_temp_cagg"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistorianTag",
            fields=[
                (
                    "tag_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag_name", models.CharField(max_length=512)),
                ("description", models.TextField(blank=True)),
                ("tag_type", models.SmallIntegerField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=128)),
                ("source_system", models.CharField(default="AVEVA", max_length=64)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "historian_tag",
                "ordering": ["tag_name"],
            },
        ),
        migrations.CreateModel(
            name="HistorianTagLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historian_links",
                        to="infrastructure.container",
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historian_links",
                        to="environmental.environmentalparameter",
                    ),
                ),
                (
                    "sensor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historian_links",
                        to="infrastructure.sensor",
                    ),
                ),
                (
                    "tag",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="link",
                        to="historian.historiantag",
                    ),
                ),
            ],
            options={
                "db_table": "historian_tag_link",
            },
        ),
        migrations.CreateModel(
            name="HistorianTagHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recorded_at", models.DateTimeField()),
                ("tag_name", models.CharField(max_length=512)),
                ("tag_type", models.SmallIntegerField(blank=True, null=True)),
                ("unit", models.CharField(blank=True, max_length=128)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="historian.historiantag",
                    ),
                ),
            ],
            options={
                "db_table": "historian_tag_history",
                "ordering": ["tag", "recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["tag", "recorded_at"],
                        name="historian_t_tag_id_b92922_idx",
                    ),
                    models.Index(
                        fields=["recorded_at"], name="historian_t_recorde_30b51c_idx"
                    ),
                ],
            },
        ),
    ]
