# Generated by Django 4.2.11 on 2025-11-24 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("historian", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historiantaghistory",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="history",
                to="historian.historiantag",
            ),
        ),
    ]
