# Generated by Django 4.2.11 on 2025-10-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "infrastructure",
            "0008_alter_area_options_alter_containertype_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DimCompany",
            fields=[
                ("company_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "subsidiary",
                    models.CharField(
                        choices=[
                            ("BS", "Broodstock"),
                            ("FW", "Freshwater"),
                            ("FM", "Farming"),
                            ("LG", "Logistics"),
                            ("ALL", "All Subsidiaries"),
                        ],
                        max_length=3,
                    ),
                ),
                ("display_name", models.CharField(max_length=150)),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "nav_company_code",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "geography",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_companies",
                        to="infrastructure.geography",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Company",
                "verbose_name_plural": "Finance Companies",
                "ordering": ("geography__name", "subsidiary"),
            },
        ),
        migrations.CreateModel(
            name="DimSite",
            fields=[
                ("site_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "source_model",
                    models.CharField(
                        choices=[("station", "Freshwater Station"), ("area", "Area")],
                        max_length=16,
                    ),
                ),
                ("source_pk", models.PositiveIntegerField()),
                ("site_name", models.CharField(max_length=150)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sites",
                        to="finance.dimcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance Site",
                "verbose_name_plural": "Finance Sites",
                "ordering": ("site_name",),
            },
        ),
        migrations.AddConstraint(
            model_name="dimsite",
            constraint=models.UniqueConstraint(
                fields=("source_model", "source_pk"),
                name="dim_site_source_model_pk_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="dimcompany",
            constraint=models.UniqueConstraint(
                fields=("geography", "subsidiary"),
                name="dim_company_geography_subsidiary_uniq",
            ),
        ),
    ]
