# Generated by Django 4.2.11 on 2025-10-06 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("harvest", "0001_initial"),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntercompanyPolicy",
            fields=[
                ("policy_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("market", "Market"),
                            ("cost_plus", "Cost Plus"),
                            ("standard", "Standard"),
                        ],
                        default="market",
                        max_length=20,
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "from_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies_outbound",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "product_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intercompany_policies",
                        to="harvest.productgrade",
                    ),
                ),
                (
                    "to_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies_inbound",
                        to="finance.dimcompany",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "from_company__geography__name",
                    "from_company__subsidiary",
                    "product_grade__code",
                ),
            },
        ),
        migrations.CreateModel(
            name="HistoricalIntercompanyTransaction",
            fields=[
                ("tx_id", models.BigIntegerField(blank=True, db_index=True)),
                ("posting_date", models.DateField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("exported", "Exported"),
                            ("posted", "Posted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="harvest.harvestevent",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.intercompanypolicy",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical intercompany transaction",
                "verbose_name_plural": "historical intercompany transactions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalIntercompanyPolicy",
            fields=[
                ("policy_id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("market", "Market"),
                            ("cost_plus", "Cost Plus"),
                            ("standard", "Standard"),
                        ],
                        default="market",
                        max_length=20,
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=6, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "from_company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_grade",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="harvest.productgrade",
                    ),
                ),
                (
                    "to_company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimcompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical intercompany policy",
                "verbose_name_plural": "historical intercompany policys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFactHarvest",
            fields=[
                ("fact_id", models.BigIntegerField(blank=True, db_index=True)),
                ("event_date", models.DateTimeField(db_index=True)),
                ("quantity_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_count", models.PositiveIntegerField()),
                ("dim_batch_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "dim_company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "dim_site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimsite",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="harvest.harvestevent",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="harvest.harvestlot",
                    ),
                ),
                (
                    "product_grade",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="harvest.productgrade",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical fact harvest",
                "verbose_name_plural": "historical fact harvests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="FactHarvest",
            fields=[
                ("fact_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_date", models.DateTimeField(db_index=True)),
                ("quantity_kg", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit_count", models.PositiveIntegerField()),
                ("dim_batch_id", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dim_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fact_harvests",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "dim_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fact_harvests",
                        to="finance.dimsite",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_facts",
                        to="harvest.harvestevent",
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_fact",
                        to="harvest.harvestlot",
                    ),
                ),
                (
                    "product_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_facts",
                        to="harvest.productgrade",
                    ),
                ),
            ],
            options={
                "ordering": ("-event_date", "fact_id"),
            },
        ),
        migrations.CreateModel(
            name="IntercompanyTransaction",
            fields=[
                ("tx_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("posting_date", models.DateField(db_index=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("exported", "Exported"),
                            ("posted", "Posted"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intercompany_transactions",
                        to="harvest.harvestevent",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="finance.intercompanypolicy",
                    ),
                ),
            ],
            options={
                "ordering": ("-posting_date", "tx_id"),
                "indexes": [
                    models.Index(
                        fields=["state", "posting_date"],
                        name="ix_interco_state_posting",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="intercompanytransaction",
            constraint=models.UniqueConstraint(
                fields=("event", "policy"),
                name="intercompany_transaction_event_policy_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="intercompanypolicy",
            constraint=models.UniqueConstraint(
                fields=("from_company", "to_company", "product_grade"),
                name="intercompany_policy_company_grade_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="factharvest",
            index=models.Index(
                fields=["event_date"], name="ix_fact_harvest_event_date"
            ),
        ),
        migrations.AddIndex(
            model_name="factharvest",
            index=models.Index(
                fields=["dim_company", "product_grade"],
                name="ix_fact_harvest_company_grade",
            ),
        ),
    ]
