# Generated by Django 4.2.11 on 2025-10-07 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("harvest", "0001_initial"),
        (
            "finance",
            "0002_intercompanypolicy_historicalintercompanytransaction_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NavExportBatch",
            fields=[
                ("batch_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("posting_date", models.DateField()),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("exported", "Exported")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nav_export_batches",
                        to="finance.dimcompany",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-batch_id"),
            },
        ),
        migrations.CreateModel(
            name="NavExportLine",
            fields=[
                ("line_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("document_no", models.CharField(max_length=32)),
                ("account_no", models.CharField(max_length=50)),
                ("balancing_account_no", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.CharField(max_length=255)),
                ("batch_id_int", models.PositiveIntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance.navexportbatch",
                    ),
                ),
                (
                    "dim_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nav_export_lines",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "dim_site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nav_export_lines",
                        to="finance.dimsite",
                    ),
                ),
                (
                    "product_grade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nav_export_lines",
                        to="harvest.productgrade",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="nav_export_lines",
                        to="finance.intercompanytransaction",
                    ),
                ),
            ],
            options={
                "ordering": ("line_id",),
            },
        ),
        migrations.CreateModel(
            name="HistoricalNavExportLine",
            fields=[
                ("line_id", models.BigIntegerField(blank=True, db_index=True)),
                ("document_no", models.CharField(max_length=32)),
                ("account_no", models.CharField(max_length=50)),
                ("balancing_account_no", models.CharField(max_length=50)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("description", models.CharField(max_length=255)),
                ("batch_id_int", models.PositiveIntegerField()),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.navexportbatch",
                    ),
                ),
                (
                    "dim_company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "dim_site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimsite",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_grade",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="harvest.productgrade",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.intercompanytransaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical nav export line",
                "verbose_name_plural": "historical nav export lines",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalNavExportBatch",
            fields=[
                ("batch_id", models.BigIntegerField(blank=True, db_index=True)),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("posting_date", models.DateField()),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[("draft", "Draft"), ("exported", "Exported")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical nav export batch",
                "verbose_name_plural": "historical nav export batchs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name="navexportline",
            constraint=models.UniqueConstraint(
                fields=("batch", "document_no"),
                name="nav_export_line_batch_document_no_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="navexportbatch",
            constraint=models.UniqueConstraint(
                fields=("company", "date_from", "date_to"),
                name="nav_export_batch_company_daterange_uniq",
            ),
        ),
    ]
