# Generated by Django 4.2.11 on 2025-11-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_finance_historical_cleanup"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalintercompanypolicy",
            name="price_per_thousand_eggs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed price per 1000 eggs for EGG_DELIVERY pricing_basis",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="intercompanypolicy",
            name="price_per_thousand_eggs",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Fixed price per 1000 eggs for EGG_DELIVERY pricing_basis",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalintercompanypolicy",
            name="pricing_basis",
            field=models.CharField(
                choices=[
                    ("grade", "Product Grade (Harvest)"),
                    ("lifecycle", "Lifecycle Stage (Transfer)"),
                    ("egg_delivery", "Egg Delivery (Creation)"),
                ],
                default="grade",
                help_text="Whether this policy is for harvest (grade) or transfer (lifecycle)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="intercompanypolicy",
            name="pricing_basis",
            field=models.CharField(
                choices=[
                    ("grade", "Product Grade (Harvest)"),
                    ("lifecycle", "Lifecycle Stage (Transfer)"),
                    ("egg_delivery", "Egg Delivery (Creation)"),
                ],
                default="grade",
                help_text="Whether this policy is for harvest (grade) or transfer (lifecycle)",
                max_length=20,
            ),
        ),
    ]
