# Generated by Django 4.2.11 on 2025-03-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0004_remove_batch_container"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batchtransfer",
            options={"ordering": ["-transfer_date", "-created_at"]},
        ),
        migrations.RemoveField(
            model_name="batchtransfer",
            name="destination_container",
        ),
        migrations.RemoveField(
            model_name="batchtransfer",
            name="source_container",
        ),
        migrations.AlterField(
            model_name="batchtransfer",
            name="is_emergency_mixing",
            field=models.BooleanField(
                default=False,
                help_text="Whether this was an emergency mixing of different batches",
            ),
        ),
    ]
