# Generated by Django 4.2.11 on 2025-04-01 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0005_remove_container_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchcontainerassignment",
            name="lifecycle_stage",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="container_assignments",
                to="batch.lifecyclestage",
            ),
            preserve_default=False,
        ),
    ]
