# Generated by Django 4.2.11 on 2025-04-28 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0008_alter_growthsample_avg_length_cm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthsample',
            name='sampling_event_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Shared identifier for associating growth and health data in sampling events.', null=True),
        ),
        migrations.AddIndex(
            model_name='growthsample',
            index=models.Index(fields=['sample_date'], name='batch_growt_sample__9efd52_idx'),
        ),
    ]
