# Generated by Django 4.2.11 on 2025-04-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0010_remove_growthsample_batch_growt_sample__9efd52_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='growthsample',
            name='sampling_event_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Identifier linking samples from the same sampling event', null=True),
        ),
    ]
