# Generated by Django 4.2.11 on 2025-06-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0005_update_feedstock_timestamps"),
        ("batch", "0014_remove_batch_avg_weight_g_remove_batch_biomass_kg_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchcontainerassignment",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_assignments",
                to="batch.batch",
            ),
        ),
        migrations.AlterField(
            model_name="batchcontainerassignment",
            name="container",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="container_assignments",
                to="infrastructure.container",
            ),
        ),
    ]
