# Generated by Django 4.2.11 on 2025-09-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0016_historicalbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchcontainerassignment",
            name="last_weighing_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the most recent growth sample (weighing) for this assignment",
                null=True,
            ),
        ),
    ]
