# Generated by Django 4.2.11 on 2025-09-11 08:30
# Updated to create proper Django migrations for missing historical tables
# instead of using populate_history command for consistency and idempotency

from django.conf import settings
from django.db import migrations, models
from django.core import validators
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batch", "0017_add_last_weighing_date"),
    ]

    operations = [
        # Historical table for BatchContainerAssignment
        migrations.CreateModel(
            name="HistoricalBatchContainerAssignment",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("population_count", models.PositiveIntegerField(validators=[validators.MinValueValidator(0)])),
                (
                    "avg_weight_g",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True,
                        help_text="Average weight in grams per fish at the time of this specific assignment or update."
                    ),
                ),
                (
                    "biomass_kg",
                    models.DecimalField(decimal_places=2, max_digits=10,
                        help_text="Total biomass in kilograms. Calculated if population_count and avg_weight_g are provided."),
                ),
                ("assignment_date", models.DateField()),
                (
                    "departure_date",
                    models.DateField(
                        blank=True,
                        help_text="Date when this specific assignment ended (e.g., fish moved out or population became zero)",
                        null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True, help_text="Whether this assignment is current/active")),
                (
                    "last_weighing_date",
                    models.DateField(
                        blank=True,
                        help_text="Date of the most recent growth sample (weighing) for this assignment",
                        null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batch",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="infrastructure.container",
                    ),
                ),
                (
                    "lifecycle_stage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.lifecyclestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical batch container assignment",
                "verbose_name_plural": "historical batch container assignments",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
