# Generated by Django 4.2.11 on 2026-03-11 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("batch", "0050_batchtransferworkflow_dynamic_completed_at_and_more"),
        ("finance", "0008_add_egg_delivery_pricing"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("account_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "finance_core_account",
                "ordering": ("account_type", "code"),
            },
        ),
        migrations.CreateModel(
            name="AccountGroup",
            fields=[
                ("group_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=150)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cost_group",
                    models.CharField(
                        blank=True,
                        help_text="External cost-group code used in NAV imports.",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="finance_core.accountgroup",
                    ),
                ),
            ],
            options={
                "db_table": "finance_core_accountgroup",
                "ordering": ("account_type", "display_order", "code"),
            },
        ),
        migrations.CreateModel(
            name="Budget",
            fields=[
                ("budget_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("fiscal_year", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_core_budgets",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_finance_core_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finance_core_budget",
                "ordering": ("-fiscal_year", "company__display_name", "name"),
            },
        ),
        migrations.CreateModel(
            name="BudgetEntry",
            fields=[
                ("entry_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("month", models.PositiveSmallIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budget_entries",
                        to="finance_core.account",
                    ),
                ),
                (
                    "allocated_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations",
                        to="finance_core.budgetentry",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="finance_core.budget",
                    ),
                ),
            ],
            options={
                "db_table": "finance_core_budgetentry",
                "ordering": (
                    "budget__fiscal_year",
                    "month",
                    "account__code",
                    "cost_center__code",
                ),
            },
        ),
        migrations.CreateModel(
            name="CostCenter",
            fields=[
                (
                    "cost_center_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                (
                    "cost_center_type",
                    models.CharField(
                        choices=[
                            ("SITE", "Site"),
                            ("PROJECT", "Project"),
                            ("DEPARTMENT", "Department"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_core_cost_centers",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="finance_core.costcenter",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_core_cost_centers",
                        to="finance.dimsite",
                    ),
                ),
            ],
            options={
                "db_table": "finance_core_costcenter",
                "ordering": ("company__display_name", "code"),
            },
        ),
        migrations.CreateModel(
            name="CostImportBatch",
            fields=[
                (
                    "import_batch_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("source_filename", models.CharField(max_length=255)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("imported_row_count", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_core_cost_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finance_core_costimportbatch",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="PeriodLock",
            fields=[
                (
                    "period_lock_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("is_locked", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("lock_reason", models.TextField(blank=True)),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("reopen_reason", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_core_period_locks",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="locked_finance_core_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operating_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_core_period_locks",
                        to="finance.dimsite",
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reopened_finance_core_periods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finance_core_periodlock",
                "ordering": (
                    "-year",
                    "-month",
                    "company__display_name",
                    "operating_unit__site_name",
                ),
            },
        ),
        migrations.CreateModel(
            name="HistoricalValuationRun",
            fields=[
                ("run_id", models.BigIntegerField(blank=True, db_index=True)),
                (
                    "run_timestamp",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Preview"),
                            ("APPROVED", "Approved"),
                            ("EXPORTED", "Exported"),
                            ("FAILED", "Failed"),
                        ],
                        default="PREVIEW",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("biology_snapshot", models.JSONField(blank=True, default=list)),
                ("allocation_snapshot", models.JSONField(blank=True, default=list)),
                ("rule_snapshot", models.JSONField(blank=True, default=list)),
                ("mortality_snapshot", models.JSONField(blank=True, default=list)),
                ("totals_snapshot", models.JSONField(blank=True, default=dict)),
                ("nav_posting", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.budget",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.costimportbatch",
                    ),
                ),
                (
                    "operating_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical valuation run",
                "verbose_name_plural": "historical valuation runs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPeriodLock",
            fields=[
                ("period_lock_id", models.BigIntegerField(blank=True, db_index=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("is_locked", models.BooleanField(default=True)),
                ("version", models.PositiveIntegerField(default=1)),
                ("lock_reason", models.TextField(blank=True)),
                ("locked_at", models.DateTimeField(blank=True, editable=False)),
                ("reopened_at", models.DateTimeField(blank=True, null=True)),
                ("reopen_reason", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "operating_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimsite",
                    ),
                ),
                (
                    "reopened_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical period lock",
                "verbose_name_plural": "historical period locks",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCostImportLine",
            fields=[
                ("line_id", models.BigIntegerField(blank=True, db_index=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("cost_group_code", models.CharField(max_length=64)),
                ("operating_unit_name", models.CharField(max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "account_group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.accountgroup",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.costimportbatch",
                    ),
                ),
                (
                    "operating_unit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cost import line",
                "verbose_name_plural": "historical cost import lines",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCostImportBatch",
            fields=[
                ("import_batch_id", models.BigIntegerField(blank=True, db_index=True)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("source_filename", models.CharField(max_length=255)),
                ("checksum", models.CharField(blank=True, max_length=64)),
                ("imported_row_count", models.PositiveIntegerField(default=0)),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cost import batch",
                "verbose_name_plural": "historical cost import batchs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCostCenterBatchLink",
            fields=[
                ("link_id", models.BigIntegerField(blank=True, db_index=True)),
                ("linked_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batch",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cost center batch link",
                "verbose_name_plural": "historical cost center batch links",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalCostCenter",
            fields=[
                ("cost_center_id", models.BigIntegerField(blank=True, db_index=True)),
                ("code", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=150)),
                (
                    "cost_center_type",
                    models.CharField(
                        choices=[
                            ("SITE", "Site"),
                            ("PROJECT", "Project"),
                            ("DEPARTMENT", "Department"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.costcenter",
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimsite",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical cost center",
                "verbose_name_plural": "historical cost centers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBudgetEntry",
            fields=[
                ("entry_id", models.BigIntegerField(blank=True, db_index=True)),
                ("month", models.PositiveSmallIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.account",
                    ),
                ),
                (
                    "allocated_from",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.budgetentry",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.budget",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.costcenter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical budget entry",
                "verbose_name_plural": "historical budget entrys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBudget",
            fields=[
                ("budget_id", models.BigIntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=150)),
                ("fiscal_year", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ACTIVE", "Active"),
                            ("ARCHIVED", "Archived"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical budget",
                "verbose_name_plural": "historical budgets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAllocationRule",
            fields=[
                ("rule_id", models.BigIntegerField(blank=True, db_index=True)),
                ("name", models.CharField(max_length=150)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("rule_definition", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "account_group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.accountgroup",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.costcenter",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical allocation rule",
                "verbose_name_plural": "historical allocation rules",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAccountGroup",
            fields=[
                ("group_id", models.BigIntegerField(blank=True, db_index=True)),
                ("code", models.CharField(db_index=True, max_length=32)),
                ("name", models.CharField(max_length=150)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cost_group",
                    models.CharField(
                        blank=True,
                        help_text="External cost-group code used in NAV imports.",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.accountgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical account group",
                "verbose_name_plural": "historical account groups",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalAccount",
            fields=[
                ("account_id", models.BigIntegerField(blank=True, db_index=True)),
                ("code", models.CharField(db_index=True, max_length=32)),
                ("name", models.CharField(max_length=150)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("ASSET", "Asset"),
                            ("LIABILITY", "Liability"),
                            ("EQUITY", "Equity"),
                            ("REVENUE", "Revenue"),
                            ("EXPENSE", "Expense"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance_core.accountgroup",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical account",
                "verbose_name_plural": "historical accounts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="CostImportLine",
            fields=[
                ("line_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("cost_group_code", models.CharField(max_length=64)),
                ("operating_unit_name", models.CharField(max_length=150)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=16)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="import_lines",
                        to="finance_core.accountgroup",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_core_import_lines",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="finance_core.costimportbatch",
                    ),
                ),
                (
                    "operating_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_core_import_lines",
                        to="finance.dimsite",
                    ),
                ),
            ],
            options={
                "db_table": "finance_core_costimportline",
                "ordering": ("year", "month", "operating_unit_name", "cost_group_code"),
            },
        ),
        migrations.CreateModel(
            name="CostCenterBatchLink",
            fields=[
                ("link_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_core_link",
                        to="batch.batch",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_links",
                        to="finance_core.costcenter",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_finance_core_batch_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finance_core_costcenterbatchlink",
                "ordering": ("batch__batch_number",),
            },
        ),
        migrations.AddField(
            model_name="budgetentry",
            name="cost_center",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budget_entries",
                to="finance_core.costcenter",
            ),
        ),
        migrations.CreateModel(
            name="AllocationRule",
            fields=[
                ("rule_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=150)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("rule_definition", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_rules",
                        to="finance_core.accountgroup",
                    ),
                ),
                (
                    "cost_center",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocation_rules",
                        to="finance_core.costcenter",
                    ),
                ),
            ],
            options={
                "db_table": "finance_core_allocationrule",
                "ordering": ("-effective_from", "name"),
            },
        ),
        migrations.AddField(
            model_name="account",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounts",
                to="finance_core.accountgroup",
            ),
        ),
        migrations.CreateModel(
            name="ValuationRun",
            fields=[
                ("run_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "run_timestamp",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PREVIEW", "Preview"),
                            ("APPROVED", "Approved"),
                            ("EXPORTED", "Exported"),
                            ("FAILED", "Failed"),
                        ],
                        default="PREVIEW",
                        max_length=20,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("biology_snapshot", models.JSONField(blank=True, default=list)),
                ("allocation_snapshot", models.JSONField(blank=True, default=list)),
                ("rule_snapshot", models.JSONField(blank=True, default=list)),
                ("mortality_snapshot", models.JSONField(blank=True, default=list)),
                ("totals_snapshot", models.JSONField(blank=True, default=dict)),
                ("nav_posting", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_finance_core_valuation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valuation_runs",
                        to="finance_core.budget",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_core_valuation_runs",
                        to="finance.dimcompany",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_finance_core_valuation_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "import_batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="valuation_runs",
                        to="finance_core.costimportbatch",
                    ),
                ),
                (
                    "operating_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="finance_core_valuation_runs",
                        to="finance.dimsite",
                    ),
                ),
            ],
            options={
                "db_table": "finance_core_valuationrun",
                "ordering": ("-year", "-month", "-version", "-run_timestamp"),
                "indexes": [
                    models.Index(
                        fields=["company", "year", "month"], name="fc_val_co_per_idx"
                    ),
                    models.Index(
                        fields=["operating_unit", "year", "month"],
                        name="fc_val_ou_per_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="periodlock",
            constraint=models.UniqueConstraint(
                fields=("company", "operating_unit", "year", "month"),
                name="finance_core_periodlock_company_operating_unit_year_month_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="costimportline",
            index=models.Index(
                fields=["year", "month", "operating_unit"], name="fc_imp_yr_mo_ou_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costimportline",
            index=models.Index(
                fields=["year", "month", "account_group"], name="fc_imp_yr_mo_grp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="valuationrun",
            index=models.Index(
                fields=["company", "operating_unit", "year", "month", "version"],
                name="fc_val_per_ver_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="costcenter",
            constraint=models.UniqueConstraint(
                fields=("company", "code"),
                name="finance_core_costcenter_company_code_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="budgetentry",
            constraint=models.UniqueConstraint(
                fields=("budget", "account", "cost_center", "month"),
                name="finance_core_budgetentry_budget_account_costcenter_month_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                fields=("company", "fiscal_year", "name", "version"),
                name="finance_core_budget_company_year_name_version_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="accountgroup",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cost_group__isnull", False)),
                fields=("cost_group",),
                name="finance_core_accountgroup_cost_group_uniq",
            ),
        ),
    ]
