# Generated by Django 4.2.11 on 2025-03-12 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Latitude (automatically set when location is selected on map)",
                max_digits=9,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Longitude (automatically set when location is selected on map)",
                max_digits=9,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="freshwaterstation",
            name="latitude",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Latitude (automatically set when location is selected on map)",
                max_digits=9,
                validators=[
                    django.core.validators.MinValueValidator(-90),
                    django.core.validators.MaxValueValidator(90),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="freshwaterstation",
            name="longitude",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Longitude (automatically set when location is selected on map)",
                max_digits=9,
                validators=[
                    django.core.validators.MinValueValidator(-180),
                    django.core.validators.MaxValueValidator(180),
                ],
            ),
        ),
    ]
