# Generated by Django 4.2.11 on 2025-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0002_alter_area_latitude_alter_area_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="max_biomass",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Maximum biomass capacity in kg",
                max_digits=12,
            ),
        ),
    ]
