# Generated by Django 4.2.11 on 2025-06-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0004_container_feed_recommendations_enabled_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="feed_recommendations_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="container",
            name="max_biomass_kg",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="container",
            name="volume_m3",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
