# Generated by Django 4.2.11 on 2025-06-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0006_historicalcontainer"),
    ]

    operations = []
