# Generated by Django 4.2.11 on 2026-02-18 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "infrastructure",
            "0008_alter_area_options_alter_containertype_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalTransportCarrier",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "carrier_type",
                    models.CharField(
                        choices=[("TRUCK", "Truck"), ("VESSEL", "Vessel")],
                        max_length=20,
                    ),
                ),
                ("capacity_m3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("license_plate", models.CharField(blank=True, max_length=32)),
                ("imo_number", models.CharField(blank=True, max_length=20)),
                ("captain_contact", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical transport carrier",
                "verbose_name_plural": "historical transport carriers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="TransportCarrier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "carrier_type",
                    models.CharField(
                        choices=[("TRUCK", "Truck"), ("VESSEL", "Vessel")],
                        max_length=20,
                    ),
                ),
                ("capacity_m3", models.DecimalField(decimal_places=2, max_digits=10)),
                ("license_plate", models.CharField(blank=True, max_length=32)),
                ("imo_number", models.CharField(blank=True, max_length=20)),
                ("captain_contact", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="transportcarrier",
            name="geography",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transport_carriers",
                to="infrastructure.geography",
            ),
        ),
        migrations.AddField(
            model_name="historicaltransportcarrier",
            name="geography",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="infrastructure.geography",
            ),
        ),
        migrations.AddField(
            model_name="historicaltransportcarrier",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tanks",
                to="infrastructure.transportcarrier",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontainer",
            name="carrier",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="infrastructure.transportcarrier",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="container",
            name="container_in_either_hall_or_area",
        ),
        migrations.AddConstraint(
            model_name="container",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("area__isnull", True),
                        ("carrier__isnull", True),
                        ("hall__isnull", False),
                    ),
                    models.Q(
                        ("area__isnull", False),
                        ("carrier__isnull", True),
                        ("hall__isnull", True),
                    ),
                    models.Q(
                        ("area__isnull", True),
                        ("carrier__isnull", False),
                        ("hall__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="container_in_hall_area_or_carrier",
            ),
        ),
    ]
