# Generated by Django 4.2.11 on 2026-02-19 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("infrastructure", "0009_historicaltransportcarrier_transportcarrier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=32)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "geography",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="area_groups",
                        to="infrastructure.geography",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="infrastructure.areagroup",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="container",
            name="hierarchy_role",
            field=models.CharField(
                choices=[("HOLDING", "Holding"), ("STRUCTURAL", "Structural")],
                default="HOLDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="container",
            name="parent_container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_containers",
                to="infrastructure.container",
            ),
        ),
        migrations.AddField(
            model_name="historicalcontainer",
            name="hierarchy_role",
            field=models.CharField(
                choices=[("HOLDING", "Holding"), ("STRUCTURAL", "Structural")],
                default="HOLDING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicalcontainer",
            name="parent_container",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="infrastructure.container",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalAreaGroup",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(blank=True, max_length=32)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "geography",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="infrastructure.geography",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="infrastructure.areagroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical area group",
                "verbose_name_plural": "historical area groups",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="area",
            name="area_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="areas",
                to="infrastructure.areagroup",
            ),
        ),
        migrations.AddField(
            model_name="historicalarea",
            name="area_group",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="infrastructure.areagroup",
            ),
        ),
        migrations.AddConstraint(
            model_name="areagroup",
            constraint=models.UniqueConstraint(
                fields=("geography", "parent", "name"),
                name="uniq_area_group_geo_parent_name",
            ),
        ),
    ]
