# Generated by Django 4.2.11 on 2025-09-10 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("users", "0003_create_ci_test_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalUserProfile",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="full name"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="phone number",
                    ),
                ),
                (
                    "profile_picture",
                    models.TextField(blank=True, max_length=100, null=True),
                ),
                ("job_title", models.CharField(blank=True, max_length=100, null=True)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "geography",
                    models.CharField(
                        choices=[
                            ("FO", "Faroe Islands"),
                            ("SC", "Scotland"),
                            ("ALL", "All Geographies"),
                        ],
                        default="ALL",
                        help_text="Geographic region access level",
                        max_length=3,
                    ),
                ),
                (
                    "subsidiary",
                    models.CharField(
                        choices=[
                            ("BS", "Broodstock"),
                            ("FW", "Freshwater"),
                            ("FM", "Farming"),
                            ("LG", "Logistics"),
                            ("ALL", "All Subsidiaries"),
                        ],
                        default="ALL",
                        help_text="Subsidiary access level",
                        max_length=3,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrator"),
                            ("MGR", "Manager"),
                            ("OPR", "Operator"),
                            ("VET", "Veterinarian"),
                            ("QA", "Quality Assurance"),
                            ("FIN", "Finance"),
                            ("VIEW", "Viewer"),
                        ],
                        default="VIEW",
                        help_text="User role and permission level",
                        max_length=5,
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fo", "Faroese"),
                            ("da", "Danish"),
                        ],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "date_format_preference",
                    models.CharField(
                        choices=[
                            ("DMY", "DD/MM/YYYY"),
                            ("MDY", "MM/DD/YYYY"),
                            ("YMD", "YYYY-MM-DD"),
                        ],
                        default="DMY",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical user profile",
                "verbose_name_plural": "historical user profiles",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
