# Generated by Django 4.2.11 on 2025-10-31 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_auto_20250910_1339"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HistoricalUser",
        ),
    ]
