# Generated by Django 4.2.11 on 2025-11-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0008_alter_area_options_alter_containertype_options_and_more",
        ),
        ("users", "0007_create_auth_historicaluser_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="allowed_areas",
            field=models.ManyToManyField(
                blank=True,
                help_text="Sea areas this operator is assigned to",
                related_name="permitted_users",
                to="infrastructure.area",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="allowed_containers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific containers this operator is assigned to",
                related_name="permitted_users",
                to="infrastructure.container",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="allowed_stations",
            field=models.ManyToManyField(
                blank=True,
                help_text="Freshwater stations this operator is assigned to",
                related_name="permitted_users",
                to="infrastructure.freshwaterstation",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalUser",
        ),
    ]
