# Generated by Django 4.2.11 on 2025-11-03 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_historicaluserprofile_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("MGR", "Manager"),
                    ("OPR", "Operator"),
                    ("VET", "Veterinarian"),
                    ("QA", "Quality Assurance"),
                    ("FIN", "Finance"),
                    ("VIEW", "Viewer"),
                ],
                default="VIEW",
                help_text="User role and permission level",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("MGR", "Manager"),
                    ("OPR", "Operator"),
                    ("VET", "Veterinarian"),
                    ("QA", "Quality Assurance"),
                    ("FIN", "Finance"),
                    ("VIEW", "Viewer"),
                ],
                default="VIEW",
                help_text="User role and permission level",
                max_length=5,
            ),
        ),
    ]
