# Generated by Django 4.2.11 on 2025-11-04 10:56

from django.db import migrations
from django.contrib.auth import get_user_model
from apps.users.models import UserProfile, Role, Geography, Subsidiary


def create_profiles_for_existing_users(apps, schema_editor):
    """
    Create UserProfile records for existing users who don't have one.

    This migration ensures that all existing users have RBAC profiles
    with appropriate default values.
    """
    User = get_user_model()

    # Default values for existing users (can be adjusted later by admins)
    default_role = Role.ADMIN  # Give admin access by default for safety
    default_geography = Geography.ALL
    default_subsidiary = Subsidiary.ALL

    # Find users without profiles
    users_without_profiles = []
    for user in User.objects.all():
        if not hasattr(user, 'profile') or user.profile is None:
            users_without_profiles.append(user)

    # Create profiles for users who don't have them
    profiles_created = 0
    for user in users_without_profiles:
        UserProfile.objects.create(
            user=user,
            role=default_role,
            geography=default_geography,
            subsidiary=default_subsidiary,
        )
        profiles_created += 1

    print(f"Created {profiles_created} UserProfile records for existing users")


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_revert_default_role_to_viewer"),
    ]

    operations = [
        migrations.RunPython(
            create_profiles_for_existing_users,
            reverse_code=migrations.RunPython.noop,  # No reverse migration needed
        ),
    ]
