# Generated by Django 4.2.11 on 2026-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_create_profiles_for_existing_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluserprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("MGR", "Manager"),
                    ("OPR", "Operator"),
                    ("SHIP_CREW", "Ship Crew"),
                    ("VET", "Veterinarian"),
                    ("QA", "Quality Assurance"),
                    ("FIN", "Finance"),
                    ("VIEW", "Viewer"),
                ],
                default="VIEW",
                help_text="User role and permission level",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("MGR", "Manager"),
                    ("OPR", "Operator"),
                    ("SHIP_CREW", "Ship Crew"),
                    ("VET", "Veterinarian"),
                    ("QA", "Quality Assurance"),
                    ("FIN", "Finance"),
                    ("VIEW", "Viewer"),
                ],
                default="VIEW",
                help_text="User role and permission level",
                max_length=20,
            ),
        ),
    ]
