# Generated by Django 4.2.11 on 2025-03-20 15:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("infrastructure", "0003_alter_area_max_biomass"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batch", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=100)),
                (
                    "size_category",
                    models.CharField(
                        choices=[
                            ("MICRO", "Micro"),
                            ("SMALL", "Small"),
                            ("MEDIUM", "Medium"),
                            ("LARGE", "Large"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pellet_size_mm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pellet size in millimeters",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "protein_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Protein content percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "fat_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Fat content percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "carbohydrate_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Carbohydrate content percentage",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Feed",
            },
        ),
        migrations.CreateModel(
            name="FeedStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_quantity_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Current amount of feed in stock (kg)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "reorder_threshold_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Threshold for reordering (kg)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_levels",
                        to="inventory.feed",
                    ),
                ),
                (
                    "feed_container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feed_stocks",
                        to="infrastructure.feedcontainer",
                    ),
                ),
            ],
            options={
                "unique_together": {("feed", "feed_container")},
            },
        ),
        migrations.CreateModel(
            name="FeedPurchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateField()),
                (
                    "quantity_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of feed purchased in kilograms",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "cost_per_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cost per kilogram",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("supplier", models.CharField(max_length=100)),
                (
                    "batch_number",
                    models.CharField(
                        blank=True, help_text="Supplier's batch number", max_length=100
                    ),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchases",
                        to="inventory.feed",
                    ),
                ),
            ],
            options={
                "ordering": ["-purchase_date"],
            },
        ),
        migrations.CreateModel(
            name="FeedingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feeding_date", models.DateField()),
                ("feeding_time", models.TimeField()),
                (
                    "amount_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount of feed used in kilograms",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "batch_biomass_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Batch biomass at time of feeding in kilograms",
                        max_digits=10,
                    ),
                ),
                (
                    "feeding_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Feeding as percentage of biomass",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "feed_conversion_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Feed Conversion Ratio (FCR)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[("MANUAL", "Manual"), ("AUTOMATIC", "Automatic")],
                        default="MANUAL",
                        max_length=50,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_events",
                        to="batch.batch",
                    ),
                ),
                (
                    "batch_assignment",
                    models.ForeignKey(
                        help_text="The specific batch-container assignment at time of feeding",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_events",
                        to="batch.batchcontainerassignment",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_events",
                        to="infrastructure.container",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_events",
                        to="inventory.feed",
                    ),
                ),
                (
                    "feed_stock",
                    models.ForeignKey(
                        blank=True,
                        help_text="The feed stock this feeding was drawn from",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="feeding_events",
                        to="inventory.feedstock",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recorded_feeding_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-feeding_date", "-feeding_time"],
            },
        ),
        migrations.CreateModel(
            name="BatchFeedingSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "total_feed_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total feed used in this period (kg)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "average_biomass_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Average biomass during period (kg)",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "average_feeding_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average feeding percentage during period",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "feed_conversion_ratio",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Feed Conversion Ratio for this period",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "growth_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Biomass growth during period (kg)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeding_summaries",
                        to="batch.batch",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Batch feeding summaries",
                "ordering": ["batch", "-period_end"],
                "unique_together": {("batch", "period_start", "period_end")},
            },
        ),
    ]
