# Generated by Django 4.2.11 on 2025-04-07 13:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_date', models.DateField(help_text='Date for which this recommendation applies')),
                ('recommended_feed_kg', models.DecimalField(decimal_places=3, help_text='Recommended feed amount in kilograms', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('feeding_percentage', models.DecimalField(decimal_places=2, help_text='Recommended feeding as percentage of biomass', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feedings_per_day', models.PositiveSmallIntegerField(default=2, help_text='Recommended number of feedings per day')),
                ('water_temperature_c', models.DecimalField(blank=True, decimal_places=2, help_text='Water temperature at time of recommendation (°C)', max_digits=5, null=True)),
                ('dissolved_oxygen_mg_l', models.DecimalField(blank=True, decimal_places=2, help_text='Dissolved oxygen at time of recommendation (mg/L)', max_digits=5, null=True)),
                ('recommendation_reason', models.TextField(help_text='Explanation of factors that influenced this recommendation')),
                ('is_followed', models.BooleanField(default=False, help_text='Whether this recommendation was followed')),
                ('expected_fcr', models.DecimalField(blank=True, decimal_places=2, help_text='Expected Feed Conversion Ratio if recommendation is followed', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_container_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_recommendations', to='batch.batchcontainerassignment')),
                ('feed', models.ForeignKey(help_text='Recommended feed type', on_delete=django.db.models.deletion.PROTECT, related_name='recommendations', to='inventory.feed')),
            ],
            options={
                'verbose_name_plural': 'Feed recommendations',
                'ordering': ['-recommended_date', '-created_at'],
                'unique_together': {('batch_container_assignment', 'recommended_date')},
            },
        ),
    ]
