# Generated by Django 4.2.11 on 2025-06-02 12:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batch", "0001_initial"),
        ("infrastructure", "0005_update_feedstock_timestamps"),
        ("inventory", "0003_remove_feed_recommendation"),
    ]

    operations = [
        migrations.RenameField(
            model_name="feedstock",
            old_name="last_updated",
            new_name="updated_at",
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="average_biomass_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average batch biomass during the period (kg)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="average_feeding_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average feeding percentage during the period",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="feed_conversion_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Feed Conversion Ratio for the period",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="growth_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Growth during the period (kg)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="period_end",
            field=models.DateField(help_text="End date of the summary period"),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="period_start",
            field=models.DateField(help_text="Start date of the summary period"),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="total_feed_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total feed used in kg during the period",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="feedingevent",
            name="batch_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific batch-container assignment this feeding applies to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feeding_events",
                to="batch.batchcontainerassignment",
            ),
        ),
        migrations.AlterField(
            model_name="feedingevent",
            name="batch_biomass_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Estimated batch biomass at time of feeding (kg)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AlterField(
            model_name="feedingevent",
            name="container",
            field=models.ForeignKey(
                help_text="Container where feeding occurred",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feeding_events",
                to="infrastructure.container",
            ),
        ),
        migrations.AlterField(
            model_name="feedingevent",
            name="feed",
            field=models.ForeignKey(
                help_text="Feed type used",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="feeding_events",
                to="inventory.feed",
            ),
        ),
        migrations.AlterField(
            model_name="feedingevent",
            name="feed_conversion_ratio",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated FCR for this feeding event",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feedingevent",
            name="feed_stock",
            field=models.ForeignKey(
                blank=True,
                help_text="Stock source for this feed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feeding_events",
                to="inventory.feedstock",
            ),
        ),
        migrations.AlterField(
            model_name="feedingevent",
            name="feeding_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Feed amount as percentage of biomass",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="feedingevent",
            name="method",
            field=models.CharField(
                choices=[
                    ("MANUAL", "Manual"),
                    ("AUTOMATIC", "Automatic Feeder"),
                    ("BROADCAST", "Broadcast"),
                ],
                default="MANUAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedingevent",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
