# Generated by Django 4.2.11 on 2025-06-10 10:30

from django.db import migrations, models
import django.core.validators
from decimal import Decimal


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_fifo_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingevent',
            name='amount_kg',
            field=models.DecimalField(
                decimal_places=4,
                help_text='Amount of feed used in kilograms',
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))]
            ),
        ),
        migrations.AlterField(
            model_name='feedingevent',
            name='feeding_percentage',
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text='Feed amount as percentage of biomass (auto-calculated)',
                max_digits=8,
                null=True
            ),
        ),
    ]
