# Generated by Django 4.2.11 on 2025-06-11 10:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_improve_feeding_precision"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="feedcontainerstock",
            new_name="inventory_f_feed_co_cd3df6_idx",
            old_name="inventory_feedcontainerstock_container_entry_idx",
        ),
        migrations.RenameIndex(
            model_name="feedcontainerstock",
            new_name="inventory_f_feed_pu_89e94c_idx",
            old_name="inventory_feedcontainerstock_purchase_idx",
        ),
        migrations.RemoveField(
            model_name="batchfeedingsummary",
            name="feed_conversion_ratio",
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="total_feed_consumed_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total feed consumed by the batch during this period (kg)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="feedingevent",
            name="batch_biomass_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Estimated batch biomass at time of feeding (kg)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="feedpurchase",
            name="cost_per_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Cost per kilogram",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="feedpurchase",
            name="quantity_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Amount of feed purchased in kilograms",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
