# Generated by Django 4.2.11 on 2025-09-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_historicalfeedstock"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchfeedingsummary",
            name="confidence_level",
            field=models.CharField(
                choices=[
                    ("VERY_HIGH", "Very High (< 10 days since weighing)"),
                    ("HIGH", "High (10-20 days since weighing)"),
                    ("MEDIUM", "Medium (20-40 days since weighing)"),
                    ("LOW", "Low (> 40 days since weighing)"),
                ],
                default="MEDIUM",
                help_text="Confidence level based on time since last weighing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="batchfeedingsummary",
            name="estimation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MEASURED", "Direct measurement from weighing events"),
                    ("INTERPOLATED", "Estimated from growth trends between weighings"),
                ],
                help_text="How the FCR value was calculated",
                max_length=20,
                null=True,
            ),
        ),
    ]
