# Generated by Django 4.2.11 on 2025-09-03 11:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0017_add_last_weighing_date"),
        ("inventory", "0009_add_fcr_confidence_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batchfeedingsummary",
            name="average_biomass_kg",
        ),
        migrations.RemoveField(
            model_name="batchfeedingsummary",
            name="confidence_level",
        ),
        migrations.RemoveField(
            model_name="batchfeedingsummary",
            name="growth_kg",
        ),
        migrations.AddField(
            model_name="batchfeedingsummary",
            name="container_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of containers contributing to this summary"
            ),
        ),
        migrations.AddField(
            model_name="batchfeedingsummary",
            name="overall_confidence_level",
            field=models.CharField(
                choices=[
                    ("VERY_HIGH", "Very High (< 10 days since weighing)"),
                    ("HIGH", "High (10-20 days since weighing)"),
                    ("MEDIUM", "Medium (20-40 days since weighing)"),
                    ("LOW", "Low (> 40 days since weighing)"),
                ],
                default="MEDIUM",
                help_text="Overall confidence level (worst case across containers)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="batchfeedingsummary",
            name="total_ending_biomass_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total batch biomass at end of period (kg)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="batchfeedingsummary",
            name="total_growth_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total batch growth during the period (kg)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="batchfeedingsummary",
            name="total_starting_biomass_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total batch biomass at start of period (kg)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="batchfeedingsummary",
            name="weighted_avg_fcr",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Weighted average FCR across all containers",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="average_feeding_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average feeding percentage across containers",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="estimation_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MEASURED", "All containers have direct measurements"),
                    ("MIXED", "Some containers use interpolation"),
                    ("INTERPOLATED", "Most containers use interpolation"),
                ],
                help_text="Overall estimation method across containers",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="fcr",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="DEPRECATED: Use weighted_avg_fcr instead",
                max_digits=5,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="total_biomass_gain_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total biomass gain (same as total_growth_kg for consistency)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="total_feed_consumed_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Total feed consumed (same as total_feed_kg for consistency)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="batchfeedingsummary",
            name="total_feed_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total feed used across all containers (kg)",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.CreateModel(
            name="ContainerFeedingSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "period_start",
                    models.DateField(help_text="Start date of the summary period"),
                ),
                (
                    "period_end",
                    models.DateField(help_text="End date of the summary period"),
                ),
                (
                    "total_feed_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total feed used in this container during the period (kg)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "starting_biomass_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Biomass at start of period (kg)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "ending_biomass_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Biomass at end of period (kg)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "growth_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Growth during the period (kg)",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "fcr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Feed Conversion Ratio for this container (total_feed_kg / growth_kg)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("VERY_HIGH", "Very High (< 10 days since weighing)"),
                            ("HIGH", "High (10-20 days since weighing)"),
                            ("MEDIUM", "Medium (20-40 days since weighing)"),
                            ("LOW", "Low (> 40 days since weighing)"),
                        ],
                        default="MEDIUM",
                        help_text="Confidence level based on time since last weighing",
                        max_length=20,
                    ),
                ),
                (
                    "estimation_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MEASURED", "Direct measurement from weighing events"),
                            (
                                "INTERPOLATED",
                                "Estimated from growth trends between weighings",
                            ),
                        ],
                        help_text="How the FCR value was calculated",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "data_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of feeding events contributing to this summary",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="container_feeding_summaries",
                        to="batch.batch",
                    ),
                ),
                (
                    "container_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feeding_summaries",
                        to="batch.batchcontainerassignment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Container feeding summaries",
                "ordering": ["container_assignment", "-period_end"],
                "indexes": [
                    models.Index(
                        fields=["batch", "period_start", "period_end"],
                        name="inventory_c_batch_i_f16328_idx",
                    ),
                    models.Index(
                        fields=["container_assignment", "period_start"],
                        name="inventory_c_contain_3994a5_idx",
                    ),
                ],
                "unique_together": {
                    ("container_assignment", "period_start", "period_end")
                },
            },
        ),
    ]
