# Generated by Django 4.2.11 on 2025-09-10 11:31

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0017_add_last_weighing_date"),
        ("infrastructure", "0007_add_container_history"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0010_add_container_level_fcr"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalFeedingEvent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("feeding_date", models.DateField()),
                ("feeding_time", models.TimeField()),
                (
                    "amount_kg",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Amount of feed used in kilograms",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "batch_biomass_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Estimated batch biomass at time of feeding (kg)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "feeding_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Feed amount as percentage of biomass (auto-calculated)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "feed_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Calculated cost of feed used in this feeding event",
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual"),
                            ("AUTOMATIC", "Automatic Feeder"),
                            ("BROADCAST", "Broadcast"),
                        ],
                        default="MANUAL",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batch",
                    ),
                ),
                (
                    "batch_assignment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="The specific batch-container assignment this feeding applies to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batchcontainerassignment",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Container where feeding occurred",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="infrastructure.container",
                    ),
                ),
                (
                    "feed",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Feed type used",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.feed",
                    ),
                ),
                (
                    "feed_stock",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Stock source for this feed",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="inventory.feedstock",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical feeding event",
                "verbose_name_plural": "historical feeding events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
