# Generated by Django 4.2.11 on 2025-10-04 11:26

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_historicalfeedingevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchfeedingsummary",
            name="average_biomass_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average biomass of the batch during this period (kg)",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
