# Generated by Django 4.2.11 on 2026-01-19 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0015_add_feeding_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="feedingevent",
            name="idx_feeding_container_date",
        ),
        migrations.RemoveIndex(
            model_name="feedingevent",
            name="idx_feeding_batch_date",
        ),
    ]
