# Generated by Django 4.2.11 on 2025-10-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0004_add_history_to_models"),
    ]

    operations = [
        # Drop HistoricalScenario table if it exists
        # Note: HistoricalScenarioModelChange was already dropped in migration 0003
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS scenario_historicalscenario CASCADE;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
