# Generated by Django 4.2.11 on 2025-11-03 11:47
# Partial no-op migration: Some historical models were removed from code.
# This migration handles cleanup of removed models and updates to remaining ones.

import django.core.validators
from django.db import migrations, models


def conditional_model_cleanup(apps, schema_editor):
    """
    Conditionally clean up historical models if they exist.
    
    HistoricalScenario and HistoricalScenarioModelChange were removed from the code,
    but their tables may or may not exist depending on database history.
    """
    pass  # Django will handle this through the migration operations


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0006_temperature_profile_day_number_fix"),
    ]

    operations = [
        # Skip RemoveField operations for historicalscenariomodelchange
        # The table doesn't exist in fresh databases, and Django will track
        # that the model is removed through DeleteModel operations below
        migrations.AlterModelOptions(
            name="temperaturereading",
            options={
                "ordering": ["profile", "day_number"],
                "verbose_name": "Temperature Reading",
                "verbose_name_plural": "Temperature Readings",
            },
        ),
        migrations.AlterField(
            model_name="historicalmortalitymodel",
            name="frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly")],
                help_text="Rate application frequency",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmortalitymodel",
            name="rate",
            field=models.FloatField(
                help_text="Mortality rate percentage (e.g., 0.1)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaltgcmodel",
            name="exponent_m",
            field=models.FloatField(
                default=0.66, help_text="Weight exponent (e.g., 0.66)"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltgcmodel",
            name="exponent_n",
            field=models.FloatField(
                default=0.33, help_text="Temperature exponent (e.g., 0.33)"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltgcmodel",
            name="tgc_value",
            field=models.FloatField(
                help_text="TGC coefficient (e.g., 0.025)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        # Use no-op for model deletions since tables may not exist
        migrations.RunPython(
            conditional_model_cleanup,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
