# Generated by Django 4.2.11 on 2025-11-03 11:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0006_temperature_profile_day_number_fix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalscenariomodelchange",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalscenariomodelchange",
            name="new_fcr_model",
        ),
        migrations.RemoveField(
            model_name="historicalscenariomodelchange",
            name="new_mortality_model",
        ),
        migrations.RemoveField(
            model_name="historicalscenariomodelchange",
            name="new_tgc_model",
        ),
        migrations.RemoveField(
            model_name="historicalscenariomodelchange",
            name="scenario",
        ),
        migrations.AlterModelOptions(
            name="temperaturereading",
            options={
                "ordering": ["profile", "day_number"],
                "verbose_name": "Temperature Reading",
                "verbose_name_plural": "Temperature Readings",
            },
        ),
        migrations.AlterField(
            model_name="historicalmortalitymodel",
            name="frequency",
            field=models.CharField(
                choices=[("daily", "Daily"), ("weekly", "Weekly")],
                help_text="Rate application frequency",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmortalitymodel",
            name="rate",
            field=models.FloatField(
                help_text="Mortality rate percentage (e.g., 0.1)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaltgcmodel",
            name="exponent_m",
            field=models.FloatField(
                default=0.66, help_text="Weight exponent (e.g., 0.66)"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltgcmodel",
            name="exponent_n",
            field=models.FloatField(
                default=0.33, help_text="Temperature exponent (e.g., 0.33)"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltgcmodel",
            name="tgc_value",
            field=models.FloatField(
                help_text="TGC coefficient (e.g., 0.025)",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalScenario",
        ),
        migrations.DeleteModel(
            name="HistoricalScenarioModelChange",
        ),
    ]
