# Generated by Django 4.2.11 on 2025-11-11 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0008_remove_historicalscenariomodelchange_history_user_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="HistoricalScenario",
                ),
                migrations.DeleteModel(
                    name="HistoricalScenarioModelChange",
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS scenario_historicalscenariomodelchange;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP TABLE IF EXISTS scenario_historicalscenario;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
        ),
    ]
