# Generated by Django 4.2.11 on 2025-11-28 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("scenario", "0009_remove_historicalscenariomodelchange_history_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectionRun",
            fields=[
                ("run_id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "run_date",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this projection run was created",
                    ),
                ),
                (
                    "run_number",
                    models.PositiveIntegerField(
                        help_text="Sequential run number for this scenario (1, 2, 3...)"
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional label (e.g., 'Baseline', 'Updated TGC')",
                        max_length=100,
                    ),
                ),
                (
                    "parameters_snapshot",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of TGC, FCR, mortality values used",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about this run"
                    ),
                ),
                (
                    "total_projections",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Total number of projection records in this run",
                    ),
                ),
                (
                    "final_weight_g",
                    models.FloatField(
                        blank=True,
                        help_text="Final average weight at end of projection",
                        null=True,
                    ),
                ),
                (
                    "final_biomass_kg",
                    models.FloatField(
                        blank=True,
                        help_text="Final biomass at end of projection",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Projection Run",
                "verbose_name_plural": "Projection Runs",
                "db_table": "scenario_projection_run",
                "ordering": ["scenario", "-run_number"],
            },
        ),
        # NOTE: Skipping removal of historical model fields as these tables don't exist
        # (history tracking was disabled for these models)
        migrations.AlterModelOptions(
            name="scenarioprojection",
            options={
                "ordering": ["projection_run", "day_number"],
                "verbose_name": "Scenario Projection",
                "verbose_name_plural": "Scenario Projections",
            },
        ),
        migrations.RemoveIndex(
            model_name="scenarioprojection",
            name="scenario_sc_scenari_182db9_idx",
        ),
        migrations.RemoveIndex(
            model_name="scenarioprojection",
            name="scenario_sc_scenari_8d8b89_idx",
        ),
        migrations.AlterField(
            model_name="scenarioprojection",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Temporary field for migration",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_old_projections",
                to="scenario.scenario",
            ),
        ),
        # NOTE: Skipping deletion of historical models as these tables don't exist
        # (history tracking was disabled for these models)
        migrations.AddField(
            model_name="projectionrun",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this run",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projection_runs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projectionrun",
            name="scenario",
            field=models.ForeignKey(
                help_text="The scenario configuration used for this run",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projection_runs",
                to="scenario.scenario",
            ),
        ),
        migrations.AddField(
            model_name="scenarioprojection",
            name="projection_run",
            field=models.ForeignKey(
                blank=True,
                help_text="The projection run this data belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projections",
                to="scenario.projectionrun",
            ),
        ),
        migrations.AddIndex(
            model_name="scenarioprojection",
            index=models.Index(
                fields=["projection_run", "projection_date"],
                name="scenario_sc_project_7a2ab2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scenarioprojection",
            index=models.Index(
                fields=["projection_run", "day_number"],
                name="scenario_sc_project_68d05b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="projectionrun",
            index=models.Index(
                fields=["scenario", "-run_date"], name="scenario_pr_scenari_58c6d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projectionrun",
            index=models.Index(
                fields=["run_number"], name="scenario_pr_run_num_231c54_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectionrun",
            unique_together={("scenario", "run_number")},
        ),
    ]
