# Generated by Django 4.2.11 on 2025-11-28 12:16

from django.db import migrations


def migrate_projections_to_runs(apps, schema_editor):
    """
    Create ProjectionRun for each Scenario with projections and link existing projections.
    """
    Scenario = apps.get_model('scenario', 'Scenario')
    ProjectionRun = apps.get_model('scenario', 'ProjectionRun')
    ScenarioProjection = apps.get_model('scenario', 'ScenarioProjection')
    
    # For each scenario that has projections
    for scenario in Scenario.objects.all():
        projections = ScenarioProjection.objects.filter(scenario=scenario)
        
        if projections.exists():
            # Create a ProjectionRun for this scenario
            projection_run = ProjectionRun.objects.create(
                scenario=scenario,
                run_number=1,  # First run
                label="Initial Run",
                parameters_snapshot={},  # Empty snapshot for migrated data
                total_projections=projections.count(),
                created_by=scenario.created_by,
            )
            
            # Calculate final metrics
            last_projection = projections.order_by('-day_number').first()
            if last_projection:
                projection_run.final_weight_g = last_projection.average_weight
                projection_run.final_biomass_kg = last_projection.biomass
                projection_run.save(update_fields=['final_weight_g', 'final_biomass_kg'])
            
            # Link all projections to this run
            projections.update(projection_run=projection_run)
    
    print(f"Created {ProjectionRun.objects.count()} projection runs")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by deleting all ProjectionRuns.
    """
    ProjectionRun = apps.get_model('scenario', 'ProjectionRun')
    ScenarioProjection = apps.get_model('scenario', 'ScenarioProjection')
    
    # Clear projection_run references
    ScenarioProjection.objects.all().update(projection_run=None)
    
    # Delete all projection runs
    ProjectionRun.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0010_add_projection_run_model"),
    ]

    operations = [
        migrations.RunPython(migrate_projections_to_runs, reverse_migration),
    ]
