# Generated by Django 4.2.11 on 2025-11-28 12:16

from django.db import migrations


def _has_column(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        description = schema_editor.connection.introspection.get_table_description(
            cursor,
            table_name,
        )
    return any(col.name == column_name for col in description)


def migrate_projections_to_runs(apps, schema_editor):
    """
    Create ProjectionRun for each Scenario with projections and link existing projections.
    """
    Scenario = apps.get_model('scenario', 'Scenario')
    ProjectionRun = apps.get_model('scenario', 'ProjectionRun')
    ScenarioProjection = apps.get_model('scenario', 'ScenarioProjection')
    db_alias = schema_editor.connection.alias
    projection_table = ScenarioProjection._meta.db_table

    # Branch-safe guard: skip data rewrite when legacy scenario link is absent.
    if not _has_column(schema_editor, projection_table, "scenario_id"):
        return
    
    # For each scenario that has projections
    for scenario in Scenario.objects.using(db_alias).all():
        projections = ScenarioProjection.objects.using(db_alias).filter(scenario=scenario)
        
        if projections.exists():
            # Create a ProjectionRun for this scenario
            projection_run = ProjectionRun.objects.using(db_alias).create(
                scenario=scenario,
                run_number=1,  # First run
                label="Initial Run",
                parameters_snapshot={},  # Empty snapshot for migrated data
                total_projections=projections.count(),
                created_by=scenario.created_by,
            )
            
            # Calculate final metrics
            last_projection = projections.order_by('-day_number').first()
            if last_projection:
                projection_run.final_weight_g = last_projection.average_weight
                projection_run.final_biomass_kg = last_projection.biomass
                projection_run.save(update_fields=['final_weight_g', 'final_biomass_kg'])
            
            # Link all projections to this run
            projections.update(projection_run=projection_run)
    
    print(f"Created {ProjectionRun.objects.using(db_alias).count()} projection runs")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by deleting all ProjectionRuns.
    """
    ProjectionRun = apps.get_model('scenario', 'ProjectionRun')
    ScenarioProjection = apps.get_model('scenario', 'ScenarioProjection')
    db_alias = schema_editor.connection.alias
    
    # Clear projection_run references
    ScenarioProjection.objects.using(db_alias).all().update(projection_run=None)
    
    # Delete all projection runs
    ProjectionRun.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0010_add_projection_run_model"),
    ]

    operations = [
        migrations.RunPython(migrate_projections_to_runs, reverse_migration),
    ]
