# Generated by Django 4.2.11 on 2025-12-02 10:33
# Fixed: Removed operations for historical tables that were already deleted in previous migrations

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0011_migrate_projections_to_runs"),
    ]

    operations = [
        # Remove the deprecated scenario field from ScenarioProjection
        # Projections now link via projection_run instead
        migrations.RemoveField(
            model_name="scenarioprojection",
            name="scenario",
        ),
    ]
