# Generated by Django 4.2.11 on 2025-12-02 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0011_migrate_projections_to_runs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalfcrmodel",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalmortalitymodel",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaltemperatureprofile",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaltgcmodel",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicaltgcmodel",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="scenarioprojection",
            name="scenario",
        ),
        migrations.DeleteModel(
            name="HistoricalBiologicalConstraints",
        ),
        migrations.DeleteModel(
            name="HistoricalFCRModel",
        ),
        migrations.DeleteModel(
            name="HistoricalMortalityModel",
        ),
        migrations.DeleteModel(
            name="HistoricalTemperatureProfile",
        ),
        migrations.DeleteModel(
            name="HistoricalTGCModel",
        ),
    ]
