# Generated by Django 4.2.11 on 2026-01-19 11:46

from django.db import migrations


HISTORICAL_TABLES = [
    "scenario_historicalbiologicalconstraints",
    "scenario_historicalfcrmodel",
    "scenario_historicalmortalitymodel",
    "scenario_historicaltemperatureprofile",
    "scenario_historicaltgcmodel",
]


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0012_remove_scenarioprojection_deprecated_scenario_field"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=f"DROP TABLE IF EXISTS {table};",
                    reverse_sql=migrations.RunSQL.noop,
                )
                for table in HISTORICAL_TABLES
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name="historicalfcrmodel",
                    name="history_user",
                ),
                migrations.RemoveField(
                    model_name="historicalmortalitymodel",
                    name="history_user",
                ),
                migrations.RemoveField(
                    model_name="historicaltemperatureprofile",
                    name="history_user",
                ),
                migrations.RemoveField(
                    model_name="historicaltgcmodel",
                    name="history_user",
                ),
                migrations.RemoveField(
                    model_name="historicaltgcmodel",
                    name="profile",
                ),
                migrations.DeleteModel(
                    name="HistoricalBiologicalConstraints",
                ),
                migrations.DeleteModel(
                    name="HistoricalFCRModel",
                ),
                migrations.DeleteModel(
                    name="HistoricalMortalityModel",
                ),
                migrations.DeleteModel(
                    name="HistoricalTemperatureProfile",
                ),
                migrations.DeleteModel(
                    name="HistoricalTGCModel",
                ),
            ],
        ),
    ]
