# Generated by Django 4.2.11 on 2025-04-15 10:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0006_batchcontainerassignment_lifecycle_stage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="growthsample",
            options={"ordering": ["assignment", "-sample_date"]},
        ),
        migrations.RemoveField(
            model_name="growthsample",
            name="batch",
        ),
        migrations.AddField(
            model_name="growthsample",
            name="assignment",
            field=models.ForeignKey(
                help_text="The specific container assignment this sample was taken from",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="growth_samples",
                to="batch.batchcontainerassignment",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="growthsample",
            name="avg_length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average length in centimeters (calculated from individual lengths if provided)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="growthsample",
            name="condition_factor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Condition factor (K) - calculated",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="growthsample",
            name="std_deviation_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Standard deviation of length (calculated from individual lengths if provided)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
