# Generated by Django 4.2.11 on 2025-05-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0012_remove_growthsample_sampling_event_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchcontainerassignment",
            name="avg_weight_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average weight in grams per fish at the time of this specific assignment or update.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="batchcontainerassignment",
            name="departure_date",
            field=models.DateField(
                blank=True,
                help_text="Date when this specific assignment ended (e.g., fish moved out or population became zero)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="batchcontainerassignment",
            name="biomass_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Total biomass in kilograms. Calculated if population_count and avg_weight_g are provided.",
                max_digits=10,
            ),
        ),
    ]
