# Generated by Django 4.2.11 on 2025-05-19 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0013_batchcontainerassignment_avg_weight_g_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="avg_weight_g",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="biomass_kg",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="population_count",
        ),
    ]
