# Generated by Django 4.2.11 on 2025-09-11 08:53
# Migration to create missing BatchTransfer historical table

from django.conf import settings
from django.db import migrations, models
from django.core import validators
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batch", "0018_create_missing_historical_tables"),
    ]

    operations = [
        # Historical table for BatchTransfer
        migrations.CreateModel(
            name="HistoricalBatchTransfer",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("transfer_type", models.CharField(max_length=20)),
                ("transfer_date", models.DateField()),
                ("source_count", models.PositiveIntegerField()),
                ("transferred_count", models.PositiveIntegerField()),
                ("mortality_count", models.PositiveIntegerField(default=0)),
                ("source_biomass_kg", models.DecimalField(max_digits=10, decimal_places=2)),
                ("transferred_biomass_kg", models.DecimalField(max_digits=10, decimal_places=2)),
                ("is_emergency_mixing", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batch",
                    ),
                ),
                (
                    "destination_batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batch",
                    ),
                ),
                (
                    "source_assignment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batchcontainerassignment",
                    ),
                ),
                (
                    "destination_assignment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batchcontainerassignment",
                    ),
                ),
                (
                    "source_lifecycle_stage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.lifecyclestage",
                    ),
                ),
                (
                    "destination_lifecycle_stage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.lifecyclestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical batch transfer",
                "verbose_name_plural": "historical batch transfers",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
