# Generated by Django 4.2.11 on 2025-09-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0017_add_last_weighing_date"),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE "batch_historicalbatchcontainerassignment" (
                "id" bigint NOT NULL,
                "population_count" integer NOT NULL,
                "avg_weight_g" numeric(10, 2) NULL,
                "biomass_kg" numeric(10, 2) NOT NULL,
                "assignment_date" date NOT NULL,
                "departure_date" date NULL,
                "is_active" boolean NOT NULL,
                "last_weighing_date" date NULL,
                "notes" text NOT NULL,
                "created_at" timestamp with time zone NOT NULL,
                "updated_at" timestamp with time zone NOT NULL,
                "history_id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                "history_date" timestamp with time zone NOT NULL,
                "history_change_reason" varchar(100) NULL,
                "history_type" varchar(1) NOT NULL,
                "history_user_id" integer NULL,
                "batch_id" bigint NULL,
                "container_id" bigint NULL,
                "lifecycle_stage_id" bigint NULL
            );
            """,
            reverse_sql='DROP TABLE IF EXISTS "batch_historicalbatchcontainerassignment";'
        ),
        migrations.RunSQL(
            """
            ALTER TABLE "batch_historicalbatchcontainerassignment"
            ADD CONSTRAINT "batch_historicalbatch_history_user_id_fk_auth_user_id"
            FOREIGN KEY ("history_user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
            """,
            reverse_sql="""
            ALTER TABLE "batch_historicalbatchcontainerassignment"
            DROP CONSTRAINT IF EXISTS "batch_historicalbatch_history_user_id_fk_auth_user_id";
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX "batch_historicalbatchcontainerassignment_id_idx" ON "batch_historicalbatchcontainerassignment" ("id");
            CREATE INDEX "batch_historicalbatchcontainerassignment_history_date_idx" ON "batch_historicalbatchcontainerassignment" ("history_date");
            CREATE INDEX "batch_historicalbatchcontainerassignment_history_user_id_idx" ON "batch_historicalbatchcontainerassignment" ("history_user_id");
            CREATE INDEX "batch_historicalbatchcontainerassignment_batch_id_idx" ON "batch_historicalbatchcontainerassignment" ("batch_id");
            CREATE INDEX "batch_historicalbatchcontainerassignment_container_id_idx" ON "batch_historicalbatchcontainerassignment" ("container_id");
            CREATE INDEX "batch_historicalbatchcontainerassignment_lifecycle_stage_id_idx" ON "batch_historicalbatchcontainerassignment" ("lifecycle_stage_id");
            """,
            reverse_sql="""
            DROP INDEX IF EXISTS "batch_historicalbatchcontainerassignment_id_idx";
            DROP INDEX IF EXISTS "batch_historicalbatchcontainerassignment_history_date_idx";
            DROP INDEX IF EXISTS "batch_historicalbatchcontainerassignment_history_user_id_idx";
            DROP INDEX IF EXISTS "batch_historicalbatchcontainerassignment_batch_id_idx";
            DROP INDEX IF EXISTS "batch_historicalbatchcontainerassignment_container_id_idx";
            DROP INDEX IF EXISTS "batch_historicalbatchcontainerassignment_lifecycle_stage_id_idx";
            """
        ),
    ]
