# Generated by Django 4.2.11 on 2025-09-11 08:54
# Migration to create missing HistoricalGrowthSample and HistoricalMortalityEvent tables

from django.conf import settings
from django.db import migrations, models
from django.core import validators
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batch", "0019_create_batchtransfer_historical_table"),
    ]

    operations = [
        # Historical table for GrowthSample
        migrations.CreateModel(
            name="HistoricalGrowthSample",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("sample_date", models.DateField()),
                ("sample_size", models.PositiveIntegerField()),
                ("avg_weight_g", models.DecimalField(max_digits=10, decimal_places=2)),
                ("avg_length_cm", models.DecimalField(max_digits=10, decimal_places=2, null=True)),
                ("std_deviation_weight", models.DecimalField(max_digits=10, decimal_places=2, null=True)),
                ("std_deviation_length", models.DecimalField(max_digits=10, decimal_places=2, null=True)),
                ("min_weight_g", models.DecimalField(max_digits=10, decimal_places=2, null=True)),
                ("max_weight_g", models.DecimalField(max_digits=10, decimal_places=2, null=True)),
                ("condition_factor", models.DecimalField(max_digits=10, decimal_places=2, null=True)),
                ("notes", models.TextField(null=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batchcontainerassignment",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical growth sample",
                "verbose_name_plural": "historical growth samples",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),

        # Historical table for MortalityEvent
        migrations.CreateModel(
            name="HistoricalMortalityEvent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("event_date", models.DateField()),
                ("count", models.PositiveIntegerField()),
                ("biomass_kg", models.DecimalField(max_digits=10, decimal_places=2)),
                ("cause", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical mortality event",
                "verbose_name_plural": "historical mortality events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
