# Generated by Django 4.2.11 on 2025-10-09 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0020_create_missing_historical_tables_part2"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalmortalityevent",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical mortality event",
                "verbose_name_plural": "historical Mortality events",
            },
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="destination_assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Destination batch-container assignment",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="batch.batchcontainerassignment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="destination_batch",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Destination batch for merges or new batch for splits; may be null for simple transfers",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="batch.batch",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="destination_lifecycle_stage",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="New lifecycle stage after transfer",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="batch.lifecyclestage",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="is_emergency_mixing",
            field=models.BooleanField(
                default=False,
                help_text="Whether this was an emergency mixing of different batches",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="mortality_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of mortalities during transfer"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="source_assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Source batch-container assignment",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="batch.batchcontainerassignment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="source_biomass_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Biomass before transfer in kg",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="source_count",
            field=models.PositiveIntegerField(
                help_text="Population count before transfer"
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="source_lifecycle_stage",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Lifecycle stage before transfer",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="batch.lifecyclestage",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="transfer_type",
            field=models.CharField(
                choices=[
                    ("CONTAINER", "Container Transfer"),
                    ("LIFECYCLE", "Lifecycle Stage Change"),
                    ("SPLIT", "Batch Split"),
                    ("MERGE", "Batch Merge"),
                    ("MIXED_TRANSFER", "Mixed Batch Transfer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="transferred_biomass_kg",
            field=models.DecimalField(
                decimal_places=2, help_text="Biomass transferred in kg", max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatchtransfer",
            name="transferred_count",
            field=models.PositiveIntegerField(help_text="Number of fish transferred"),
        ),
        migrations.AlterField(
            model_name="historicalgrowthsample",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The specific container assignment this sample was taken from",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="batch.batchcontainerassignment",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgrowthsample",
            name="avg_length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average length (cm) calculated from individual measurements if provided, otherwise manually entered.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgrowthsample",
            name="avg_weight_g",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Average weight (g) calculated from individual measurements if provided, otherwise manually entered.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgrowthsample",
            name="condition_factor",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Average Condition Factor (K) calculated from individual measurements if provided.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgrowthsample",
            name="max_weight_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Maximum weight in grams",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgrowthsample",
            name="min_weight_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Minimum weight in grams",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgrowthsample",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalgrowthsample",
            name="sample_size",
            field=models.PositiveIntegerField(help_text="Number of fish sampled"),
        ),
        migrations.AlterField(
            model_name="historicalgrowthsample",
            name="std_deviation_length",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Standard deviation of length (cm) calculated from individual measurements if provided.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgrowthsample",
            name="std_deviation_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Standard deviation of weight (g) calculated from individual measurements if provided.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmortalityevent",
            name="biomass_kg",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Estimated biomass lost in kg",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmortalityevent",
            name="cause",
            field=models.CharField(
                choices=[
                    ("DISEASE", "Disease"),
                    ("HANDLING", "Handling"),
                    ("PREDATION", "Predation"),
                    ("ENVIRONMENTAL", "Environmental"),
                    ("UNKNOWN", "Unknown"),
                    ("OTHER", "Other"),
                ],
                default="UNKNOWN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmortalityevent",
            name="count",
            field=models.PositiveIntegerField(help_text="Number of mortalities"),
        ),
        migrations.AlterField(
            model_name="historicalmortalityevent",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
