# Generated by Django 4.2.11 on 2025-11-03 11:46
# This migration is a no-op because migration 0024 already dropped the tables.
# However, Django needs this migration to recognize that the models no longer exist.

from django.db import migrations


def noop_forward(apps, schema_editor):
    """
    No-op forward migration.
    
    The BatchTransfer and HistoricalBatchTransfer tables were already dropped
    by migration 0024. This migration exists only to inform Django that these
    models no longer exist in the codebase.
    """
    pass


def noop_reverse(apps, schema_editor):
    """No-op reverse migration."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0025_add_individual_growth_observations"),
    ]

    operations = [
        # Use RunPython no-op instead of RemoveField/DeleteModel operations
        # since the tables were already dropped by migration 0024
        migrations.RunPython(
            noop_forward,
            reverse_code=noop_reverse,
            elidable=True,
        ),
    ]
