# Generated by Django 4.2.11 on 2025-11-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0025_add_individual_growth_observations"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalbatchtransfer",
            name="destination_assignment",
        ),
        migrations.RemoveField(
            model_name="historicalbatchtransfer",
            name="destination_batch",
        ),
        migrations.RemoveField(
            model_name="historicalbatchtransfer",
            name="destination_lifecycle_stage",
        ),
        migrations.RemoveField(
            model_name="historicalbatchtransfer",
            name="history_user",
        ),
        migrations.RemoveField(
            model_name="historicalbatchtransfer",
            name="source_assignment",
        ),
        migrations.RemoveField(
            model_name="historicalbatchtransfer",
            name="source_batch",
        ),
        migrations.RemoveField(
            model_name="historicalbatchtransfer",
            name="source_lifecycle_stage",
        ),
        migrations.DeleteModel(
            name="BatchTransfer",
        ),
        migrations.DeleteModel(
            name="HistoricalBatchTransfer",
        ),
    ]
