# Generated by Django 4.2.11 on 2025-11-11 16:24

from django.db import migrations, models


def seed_lifecycle_stage_durations(apps, schema_editor):
    """
    Seed typical_duration_days for existing lifecycle stages.
    
    Bakkafrost-specific durations:
    - Egg/Alevin: 90 days (combined stage)
    - Fry: 90 days
    - Parr: 90 days
    - Smolt: 90 days
    - Post-Smolt: 90 days
    - Adult: 400 days
    """
    LifeCycleStage = apps.get_model('batch', 'LifeCycleStage')
    
    # Map stage names (case-insensitive) to typical durations
    stage_durations = {
        'egg': 90,
        'alevin': 90,
        'egg/alevin': 90,
        'fry': 90,
        'parr': 90,
        'smolt': 90,
        'post-smolt': 90,
        'post smolt': 90,
        'adult': 400,
    }
    
    # Update existing lifecycle stages
    for stage in LifeCycleStage.objects.all():
        stage_name_lower = stage.name.lower()
        
        # Try exact match first
        if stage_name_lower in stage_durations:
            stage.typical_duration_days = stage_durations[stage_name_lower]
            stage.save(update_fields=['typical_duration_days'])
        # Try partial matches for compound names
        else:
            for key, duration in stage_durations.items():
                if key in stage_name_lower or stage_name_lower in key:
                    stage.typical_duration_days = duration
                    stage.save(update_fields=['typical_duration_days'])
                    break


def reverse_seed_lifecycle_stage_durations(apps, schema_editor):
    """
    Reverse migration: Clear typical_duration_days values.
    """
    LifeCycleStage = apps.get_model('batch', 'LifeCycleStage')
    LifeCycleStage.objects.all().update(typical_duration_days=None)


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0028_remove_partial_harvest_workflow_type"),
    ]

    operations = [
        # State-only cleanup for BatchTransfer (tables don't exist in DB anymore)
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="historicalbatchtransfer",
                    name="destination_assignment",
                ),
                migrations.RemoveField(
                    model_name="historicalbatchtransfer",
                    name="destination_batch",
                ),
                migrations.RemoveField(
                    model_name="historicalbatchtransfer",
                    name="destination_lifecycle_stage",
                ),
                migrations.RemoveField(
                    model_name="historicalbatchtransfer",
                    name="history_user",
                ),
                migrations.RemoveField(
                    model_name="historicalbatchtransfer",
                    name="source_assignment",
                ),
                migrations.RemoveField(
                    model_name="historicalbatchtransfer",
                    name="source_batch",
                ),
                migrations.RemoveField(
                    model_name="historicalbatchtransfer",
                    name="source_lifecycle_stage",
                ),
            ],
            database_operations=[],  # Don't touch database - tables already gone
        ),
        migrations.AddField(
            model_name="historicallifecyclestage",
            name="typical_duration_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Typical duration for this stage (days) - used for capacity planning",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lifecyclestage",
            name="typical_duration_days",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Typical duration for this stage (days) - used for capacity planning",
                null=True,
            ),
        ),
        # Seed typical durations for existing lifecycle stages
        migrations.RunPython(
            seed_lifecycle_stage_durations,
            reverse_seed_lifecycle_stage_durations,
        ),
        # State-only cleanup for BatchTransfer models
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="BatchTransfer",
                ),
                migrations.DeleteModel(
                    name="HistoricalBatchTransfer",
                ),
            ],
            database_operations=[],  # Don't touch database - tables already gone
        ),
    ]
