# Generated by Django 4.2.11 on 2025-11-11 16:54

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("broodstock", "0004_add_history_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batch", "0029_add_lifecycle_stage_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchCreationWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow_number",
                    models.CharField(
                        help_text="Unique workflow identifier (e.g. CRT-2025-001)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "egg_source_type",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal Broodstock"),
                            ("EXTERNAL", "External Supplier"),
                        ],
                        help_text="Whether eggs are from internal broodstock or external supplier",
                        max_length=20,
                    ),
                ),
                (
                    "external_supplier_batch_number",
                    models.CharField(
                        blank=True,
                        help_text="Supplier's batch/lot number for traceability",
                        max_length=100,
                    ),
                ),
                (
                    "external_cost_per_thousand",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per 1000 eggs (for external procurement)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_eggs_planned",
                    models.PositiveIntegerField(
                        help_text="Total eggs expected to be delivered across all actions"
                    ),
                ),
                (
                    "total_eggs_received",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Actual eggs received (planned - mortality)",
                    ),
                ),
                (
                    "total_mortality_on_arrival",
                    models.PositiveIntegerField(
                        default=0, help_text="Total DOA (dead on arrival) eggs"
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(help_text="When first delivery is planned"),
                ),
                (
                    "planned_completion_date",
                    models.DateField(
                        help_text="When all deliveries should be complete"
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True,
                        help_text="When first delivery actually occurred",
                        null=True,
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="When all deliveries were actually completed",
                        null=True,
                    ),
                ),
                (
                    "total_actions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of delivery actions"
                    ),
                ),
                (
                    "actions_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of actions completed"
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of actions completed",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for cancellation (required if status = CANCELLED)",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="When workflow was cancelled", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes about this batch creation"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "batch_creationworkflow",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="batch",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned - Awaiting Delivery"),
                    ("RECEIVING", "Receiving - Partial Delivery"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("TERMINATED", "Terminated"),
                    ("CANCELLED", "Cancelled - Never Delivered"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("PLANNED", "Planned - Awaiting Delivery"),
                    ("RECEIVING", "Receiving - Partial Delivery"),
                    ("ACTIVE", "Active"),
                    ("COMPLETED", "Completed"),
                    ("TERMINATED", "Terminated"),
                    ("CANCELLED", "Cancelled - Never Delivered"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalCreationAction",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "action_number",
                    models.PositiveIntegerField(
                        help_text="Sequential action number within workflow (1, 2, 3...)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "egg_count_planned",
                    models.PositiveIntegerField(
                        help_text="Number of eggs planned for this delivery"
                    ),
                ),
                (
                    "egg_count_actual",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Actual number of eggs delivered (if different from planned)",
                        null=True,
                    ),
                ),
                (
                    "mortality_on_arrival",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of eggs DOA (dead on arrival)"
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(
                        help_text="Expected delivery date for this action"
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual delivery date (when executed)",
                        null=True,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRANSPORT", "Ground Transport"),
                            ("HELICOPTER", "Helicopter"),
                            ("BOAT", "Boat"),
                            ("INTERNAL_TRANSFER", "Internal Facility Transfer"),
                        ],
                        help_text="Method of egg delivery",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "water_temp_on_arrival",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Water temperature in destination container (°C)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "egg_quality_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Visual egg quality score on arrival (1=poor, 5=excellent)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "execution_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of delivery operation (minutes)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes about this delivery (transport conditions, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "dest_assignment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Destination container assignment (tray/tank)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batchcontainerassignment",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who executed this delivery",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Parent batch creation workflow",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batchcreationworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical creation action",
                "verbose_name_plural": "historical creation actions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBatchCreationWorkflow",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "workflow_number",
                    models.CharField(
                        db_index=True,
                        help_text="Unique workflow identifier (e.g. CRT-2025-001)",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PLANNED", "Planned"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "egg_source_type",
                    models.CharField(
                        choices=[
                            ("INTERNAL", "Internal Broodstock"),
                            ("EXTERNAL", "External Supplier"),
                        ],
                        help_text="Whether eggs are from internal broodstock or external supplier",
                        max_length=20,
                    ),
                ),
                (
                    "external_supplier_batch_number",
                    models.CharField(
                        blank=True,
                        help_text="Supplier's batch/lot number for traceability",
                        max_length=100,
                    ),
                ),
                (
                    "external_cost_per_thousand",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Cost per 1000 eggs (for external procurement)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_eggs_planned",
                    models.PositiveIntegerField(
                        help_text="Total eggs expected to be delivered across all actions"
                    ),
                ),
                (
                    "total_eggs_received",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Actual eggs received (planned - mortality)",
                    ),
                ),
                (
                    "total_mortality_on_arrival",
                    models.PositiveIntegerField(
                        default=0, help_text="Total DOA (dead on arrival) eggs"
                    ),
                ),
                (
                    "planned_start_date",
                    models.DateField(help_text="When first delivery is planned"),
                ),
                (
                    "planned_completion_date",
                    models.DateField(
                        help_text="When all deliveries should be complete"
                    ),
                ),
                (
                    "actual_start_date",
                    models.DateField(
                        blank=True,
                        help_text="When first delivery actually occurred",
                        null=True,
                    ),
                ),
                (
                    "actual_completion_date",
                    models.DateField(
                        blank=True,
                        help_text="When all deliveries were actually completed",
                        null=True,
                    ),
                ),
                (
                    "total_actions",
                    models.PositiveIntegerField(
                        default=0, help_text="Total number of delivery actions"
                    ),
                ),
                (
                    "actions_completed",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of actions completed"
                    ),
                ),
                (
                    "progress_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Percentage of actions completed",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "cancellation_reason",
                    models.TextField(
                        blank=True,
                        help_text="Reason for cancellation (required if status = CANCELLED)",
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, help_text="When workflow was cancelled", null=True
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="General notes about this batch creation"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Batch created by this workflow (status: PLANNED initially)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batch",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who cancelled this workflow",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who created this workflow",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "egg_production",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Link to broodstock egg production event (if internal)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="broodstock.eggproduction",
                    ),
                ),
                (
                    "external_supplier",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="External egg supplier (if not internal broodstock)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="broodstock.eggsupplier",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical batch creation workflow",
                "verbose_name_plural": "historical batch creation workflows",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="batchcreationworkflow",
            name="batch",
            field=models.ForeignKey(
                help_text="Batch created by this workflow (status: PLANNED initially)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="creation_workflows",
                to="batch.batch",
            ),
        ),
        migrations.AddField(
            model_name="batchcreationworkflow",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who cancelled this workflow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_creation_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batchcreationworkflow",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this workflow",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_creation_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batchcreationworkflow",
            name="egg_production",
            field=models.ForeignKey(
                blank=True,
                help_text="Link to broodstock egg production event (if internal)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="creation_workflows",
                to="broodstock.eggproduction",
            ),
        ),
        migrations.AddField(
            model_name="batchcreationworkflow",
            name="external_supplier",
            field=models.ForeignKey(
                blank=True,
                help_text="External egg supplier (if not internal broodstock)",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="creation_workflows",
                to="broodstock.eggsupplier",
            ),
        ),
        migrations.CreateModel(
            name="CreationAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_number",
                    models.PositiveIntegerField(
                        help_text="Sequential action number within workflow (1, 2, 3...)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("SKIPPED", "Skipped"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "egg_count_planned",
                    models.PositiveIntegerField(
                        help_text="Number of eggs planned for this delivery"
                    ),
                ),
                (
                    "egg_count_actual",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Actual number of eggs delivered (if different from planned)",
                        null=True,
                    ),
                ),
                (
                    "mortality_on_arrival",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of eggs DOA (dead on arrival)"
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(
                        help_text="Expected delivery date for this action"
                    ),
                ),
                (
                    "actual_delivery_date",
                    models.DateField(
                        blank=True,
                        help_text="Actual delivery date (when executed)",
                        null=True,
                    ),
                ),
                (
                    "delivery_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TRANSPORT", "Ground Transport"),
                            ("HELICOPTER", "Helicopter"),
                            ("BOAT", "Boat"),
                            ("INTERNAL_TRANSFER", "Internal Facility Transfer"),
                        ],
                        help_text="Method of egg delivery",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "water_temp_on_arrival",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Water temperature in destination container (°C)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "egg_quality_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Visual egg quality score on arrival (1=poor, 5=excellent)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "execution_duration_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Duration of delivery operation (minutes)",
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Notes about this delivery (transport conditions, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dest_assignment",
                    models.ForeignKey(
                        help_text="Destination container assignment (tray/tank)",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="creation_actions_as_dest",
                        to="batch.batchcontainerassignment",
                    ),
                ),
                (
                    "executed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who executed this delivery",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="executed_creation_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        help_text="Parent batch creation workflow",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="batch.batchcreationworkflow",
                    ),
                ),
            ],
            options={
                "db_table": "batch_creationaction",
                "ordering": ["workflow", "action_number"],
                "indexes": [
                    models.Index(
                        fields=["workflow", "status"],
                        name="batch_creat_workflo_eea6dc_idx",
                    ),
                    models.Index(
                        fields=["expected_delivery_date"],
                        name="batch_creat_expecte_8f0f08_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="creationaction",
            constraint=models.UniqueConstraint(
                fields=("workflow", "action_number"),
                name="creation_action_workflow_number_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="batchcreationworkflow",
            index=models.Index(fields=["status"], name="batch_creat_status_b5c8e8_idx"),
        ),
        migrations.AddIndex(
            model_name="batchcreationworkflow",
            index=models.Index(
                fields=["egg_source_type"], name="batch_creat_egg_sou_1926d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="batchcreationworkflow",
            index=models.Index(
                fields=["planned_start_date"], name="batch_creat_planned_60a745_idx"
            ),
        ),
    ]
