# Generated by Django 4.2.11 on 2025-11-14 17:59

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0008_alter_area_options_alter_containertype_options_and_more",
        ),
        ("batch", "0032_add_pinned_scenario_to_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActualDailyAssignmentState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        db_index=True, help_text="The date for this daily state"
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        help_text="Days since batch start (1, 2, 3, ...)"
                    ),
                ),
                (
                    "avg_weight_g",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Computed average weight in grams",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "population",
                    models.PositiveIntegerField(
                        help_text="Computed population count",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "biomass_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Computed biomass in kilograms (population * avg_weight / 1000)",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "temp_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Temperature in Celsius (measured, interpolated, or from profile)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "mortality_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Daily mortality count (actual or modeled)"
                    ),
                ),
                (
                    "feed_kg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Daily feed in kilograms (actual or none)",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "observed_fcr",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Observed Feed Conversion Ratio (if calculable)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "anchor_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("growth_sample", "Growth Sample"),
                            ("transfer", "Transfer with Measured Weight"),
                            ("vaccination", "Vaccination with Weighing"),
                            ("manual", "Manual Admin Anchor"),
                        ],
                        help_text="Type of anchor if this is an anchor point",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "sources",
                    models.JSONField(
                        default=dict,
                        help_text="Data sources for each component (temp: measured|interpolated|profile, weight: measured|tgc_computed, etc.)",
                    ),
                ),
                (
                    "confidence_scores",
                    models.JSONField(
                        default=dict,
                        help_text="Confidence scores (0-1) for each component based on data quality and recency",
                    ),
                ),
                (
                    "last_computed_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when this state was last computed",
                    ),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        help_text="Batch-container assignment this state belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_states",
                        to="batch.batchcontainerassignment",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Batch (denormalized for efficient querying)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_states",
                        to="batch.batch",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        help_text="Container (denormalized for efficient querying)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_states",
                        to="infrastructure.container",
                    ),
                ),
                (
                    "lifecycle_stage",
                    models.ForeignKey(
                        help_text="Lifecycle stage on this date",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="daily_states",
                        to="batch.lifecyclestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actual Daily Assignment State",
                "verbose_name_plural": "Actual Daily Assignment States",
                "db_table": "batch_actualdailyassignmentstate",
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["assignment", "date"], name="idx_assignment_date"
                    ),
                    models.Index(fields=["batch", "date"], name="idx_batch_date"),
                    models.Index(fields=["date"], name="idx_date"),
                    models.Index(fields=["anchor_type"], name="idx_anchor_type"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="actualdailyassignmentstate",
            constraint=models.UniqueConstraint(
                fields=("assignment", "date"), name="unique_assignment_date"
            ),
        ),
    ]
