# Generated by Django 4.2.11 on 2025-11-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0034_timescaledb_setup_skip_for_dev"),
        ("batch", "0034_update_daily_state_primary_key"),
        ("batch", "0035_fix_observed_fcr_precision"),
    ]

    operations = []
