# Generated by Django 4.2.11 on 2025-11-18 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0036_merge_20251117_1232"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmortalityevent",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Container-specific assignment where mortality occurred",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="batch.batchcontainerassignment",
            ),
        ),
        migrations.AddField(
            model_name="mortalityevent",
            name="assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Container-specific assignment where mortality occurred",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mortality_events",
                to="batch.batchcontainerassignment",
            ),
        ),
    ]
