# Generated by Django 4.2.11 on 2025-11-28 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("scenario", "0010_add_projection_run_model"),
        ("batch", "0038_add_growth_analysis_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="batchcontainerassignment",
            name="idx_bca_batch_assign_date",
        ),
        migrations.RemoveIndex(
            model_name="batchcontainerassignment",
            name="idx_bca_batch_depart_date",
        ),
        migrations.RemoveIndex(
            model_name="mortalityevent",
            name="idx_mortality_assign_date",
        ),
        migrations.RemoveIndex(
            model_name="transferaction",
            name="idx_transfer_dest_date_status",
        ),
        migrations.RemoveIndex(
            model_name="transferaction",
            name="idx_transfer_src_date_status",
        ),
        migrations.AddField(
            model_name="batch",
            name="pinned_projection_run",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific projection run used for growth analysis. Provides version control for projections.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_batches",
                to="scenario.projectionrun",
                verbose_name="Pinned Projection Run",
            ),
        ),
        migrations.AddField(
            model_name="historicalbatch",
            name="pinned_projection_run",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Specific projection run used for growth analysis. Provides version control for projections.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="scenario.projectionrun",
                verbose_name="Pinned Projection Run",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="pinned_scenario",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use pinned_projection_run instead. Will be removed after data migration.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pinned_batches",
                to="scenario.scenario",
                verbose_name="Pinned Scenario (Deprecated)",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbatch",
            name="pinned_scenario",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="DEPRECATED: Use pinned_projection_run instead. Will be removed after data migration.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="scenario.scenario",
                verbose_name="Pinned Scenario (Deprecated)",
            ),
        ),
    ]
