# Generated by Django 4.2.11 on 2025-11-28 12:16

from django.db import migrations


def migrate_pinned_scenario_to_run(apps, schema_editor):
    """
    For each Batch with pinned_scenario, set pinned_projection_run to that scenario's latest run.
    """
    Batch = apps.get_model('batch', 'Batch')
    ProjectionRun = apps.get_model('scenario', 'ProjectionRun')
    
    migrated_count = 0
    for batch in Batch.objects.filter(pinned_scenario__isnull=False):
        # Get the latest (should be only) projection run for this scenario
        latest_run = ProjectionRun.objects.filter(scenario=batch.pinned_scenario).order_by('-run_number').first()
        
        if latest_run:
            batch.pinned_projection_run = latest_run
            batch.save(update_fields=['pinned_projection_run'])
            migrated_count += 1
    
    print(f"Migrated {migrated_count} batches from pinned_scenario to pinned_projection_run")


def reverse_migration(apps, schema_editor):
    """
    Reverse by clearing pinned_projection_run (keeping pinned_scenario intact).
    """
    Batch = apps.get_model('batch', 'Batch')
    Batch.objects.all().update(pinned_projection_run=None)


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0039_add_pinned_projection_run"),
        ("scenario", "0011_migrate_projections_to_runs"),  # Ensure projection runs exist
    ]

    operations = [
        migrations.RunPython(migrate_pinned_scenario_to_run, reverse_migration),
    ]
