# Generated by Django 4.2.11 on 2025-12-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
        ("batch", "0040_migrate_pinned_scenario_to_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchtransferworkflow",
            name="planned_activity",
            field=models.OneToOneField(
                blank=True,
                help_text="Planned activity that spawned this workflow (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spawned_workflow",
                to="planning.plannedactivity",
            ),
        ),
        migrations.AddField(
            model_name="historicalbatchtransferworkflow",
            name="planned_activity",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Planned activity that spawned this workflow (if any)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="planning.plannedactivity",
            ),
        ),
    ]
