# Generated by Django 4.2.11 on 2025-12-10 12:27
# Modified for TimescaleDB hypertable compatibility and SQLite CI support

from django.db import migrations, models, connection


def add_planned_activity_column(apps, schema_editor):
    """Add planned_activity_id column if it doesn't exist."""
    vendor = connection.vendor
    table_name = "batch_actualdailyassignmentstate"
    column_name = "planned_activity_id"
    
    # Check if column already exists
    with connection.cursor() as cursor:
        if vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info({table_name})")
            columns = [row[1] for row in cursor.fetchall()]
            column_exists = column_name in columns
        else:
            # PostgreSQL
            cursor.execute("""
                SELECT column_name FROM information_schema.columns 
                WHERE table_name = %s AND column_name = %s
            """, [table_name, column_name])
            column_exists = cursor.fetchone() is not None
    
    # Add column if it doesn't exist
    if not column_exists:
        with connection.cursor() as cursor:
            cursor.execute(f"""
                ALTER TABLE {table_name} 
                ADD COLUMN {column_name} INTEGER NULL
            """)


def remove_planned_activity_column(apps, schema_editor):
    """Remove planned_activity_id column if it exists."""
    vendor = connection.vendor
    table_name = "batch_actualdailyassignmentstate"
    column_name = "planned_activity_id"
    
    # Check if column exists
    with connection.cursor() as cursor:
        if vendor == 'sqlite':
            cursor.execute(f"PRAGMA table_info({table_name})")
            columns = [row[1] for row in cursor.fetchall()]
            column_exists = column_name in columns
        else:
            # PostgreSQL
            cursor.execute("""
                SELECT column_name FROM information_schema.columns 
                WHERE table_name = %s AND column_name = %s
            """, [table_name, column_name])
            column_exists = cursor.fetchone() is not None
    
    # Drop column if it exists (SQLite < 3.35 doesn't support DROP COLUMN)
    if column_exists:
        with connection.cursor() as cursor:
            if vendor == 'sqlite':
                # SQLite 3.35+ supports DROP COLUMN, but for older versions
                # we just skip - the column will be ignored
                import sqlite3
                if sqlite3.sqlite_version_info >= (3, 35, 0):
                    cursor.execute(f"""
                        ALTER TABLE {table_name} 
                        DROP COLUMN {column_name}
                    """)
                # else: skip for older SQLite versions
            else:
                cursor.execute(f"""
                    ALTER TABLE {table_name} 
                    DROP COLUMN {column_name}
                """)


class Migration(migrations.Migration):
    """
    Add planned_activity field to ActualDailyAssignmentState.
    
    Note: ActualDailyAssignmentState is a TimescaleDB hypertable with columnstore.
    We cannot add FK constraints directly, so we:
    1. Add the column as a simple integer using database-agnostic Python
    2. Let Django ORM handle the FK logic at application level
    """

    dependencies = [
        ("planning", "0003_add_harvest_activity_type"),
        ("batch", "0042_remove_batch_pinned_scenario"),
    ]

    operations = [
        # Add the column using Python for database compatibility
        migrations.RunPython(
            add_planned_activity_column,
            remove_planned_activity_column,
        ),
        # Update anchor_type choices (this is a regular ALTER, should work)
        migrations.AlterField(
            model_name="actualdailyassignmentstate",
            name="anchor_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("growth_sample", "Growth Sample"),
                    ("transfer", "Transfer with Measured Weight"),
                    ("vaccination", "Vaccination with Weighing"),
                    ("manual", "Manual Admin Anchor"),
                    ("planned_activity", "Completed Planned Activity"),
                ],
                help_text="Type of anchor if this is an anchor point",
                max_length=20,
                null=True,
            ),
        ),
    ]
