# Generated by Django 4.2.11 on 2025-12-10 12:27
# Modified for TimescaleDB hypertable compatibility

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add planned_activity field to ActualDailyAssignmentState.
    
    Note: ActualDailyAssignmentState is a TimescaleDB hypertable with columnstore.
    We cannot add FK constraints directly, so we:
    1. Add the column as a simple integer using raw SQL
    2. Let Django ORM handle the FK logic at application level
    """

    dependencies = [
        ("planning", "0003_add_harvest_activity_type"),
        ("batch", "0042_remove_batch_pinned_scenario"),
    ]

    operations = [
        # Add the column using raw SQL (bypasses FK constraint issue)
        migrations.RunSQL(
            sql="""
                ALTER TABLE batch_actualdailyassignmentstate 
                ADD COLUMN IF NOT EXISTS planned_activity_id INTEGER NULL;
            """,
            reverse_sql="""
                ALTER TABLE batch_actualdailyassignmentstate 
                DROP COLUMN IF EXISTS planned_activity_id;
            """,
        ),
        # Update anchor_type choices (this is a regular ALTER, should work)
        migrations.AlterField(
            model_name="actualdailyassignmentstate",
            name="anchor_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("growth_sample", "Growth Sample"),
                    ("transfer", "Transfer with Measured Weight"),
                    ("vaccination", "Vaccination with Weighing"),
                    ("manual", "Manual Admin Anchor"),
                    ("planned_activity", "Completed Planned Activity"),
                ],
                help_text="Type of anchor if this is an anchor point",
                max_length=20,
                null=True,
            ),
        ),
    ]
