# Generated by Django 4.2.11 on 2025-12-10 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0003_add_harvest_activity_type"),
        ("batch", "0042_remove_batch_pinned_scenario"),
    ]

    operations = [
        migrations.AddField(
            model_name="actualdailyassignmentstate",
            name="planned_activity",
            field=models.ForeignKey(
                blank=True,
                help_text="PlannedActivity that anchored this state (if completed activity provided weights)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="anchored_daily_states",
                to="planning.plannedactivity",
            ),
        ),
        migrations.AlterField(
            model_name="actualdailyassignmentstate",
            name="anchor_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("growth_sample", "Growth Sample"),
                    ("transfer", "Transfer with Measured Weight"),
                    ("vaccination", "Vaccination with Weighing"),
                    ("manual", "Manual Admin Anchor"),
                    ("planned_activity", "Completed Planned Activity"),
                ],
                help_text="Type of anchor if this is an anchor point",
                max_length=20,
                null=True,
            ),
        ),
    ]
