# Generated by Django 4.2.11 on 2026-01-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0008_alter_area_options_alter_containertype_options_and_more",
        ),
        ("planning", "0003_add_harvest_activity_type"),
        ("batch", "0046_add_allow_mixed_to_historicaltransferaction"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name="actualdailyassignmentstate",
                    name="planned_activity",
                    field=models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="PlannedActivity that anchored this state (if completed activity provided weights)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="anchored_daily_states",
                        to="planning.plannedactivity",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="containerforecastsummary",
            name="computed_date",
            field=models.DateField(
                blank=True,
                help_text="Date of projection run that generated this summary",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="containerforecastsummary",
            name="harvest_variance_days",
            field=models.IntegerField(
                blank=True,
                help_text="Days behind (+) or ahead (-) of original plan",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="containerforecastsummary",
            name="has_planned_harvest",
            field=models.BooleanField(
                default=False,
                help_text="PlannedActivity(HARVEST) exists for batch/container",
            ),
        ),
        migrations.AlterField(
            model_name="containerforecastsummary",
            name="has_planned_transfer",
            field=models.BooleanField(
                default=False,
                help_text="PlannedActivity(TRANSFER) exists for batch/container",
            ),
        ),
        migrations.AlterField(
            model_name="containerforecastsummary",
            name="last_computed",
            field=models.DateTimeField(
                auto_now=True, help_text="Timestamp when this summary was last updated"
            ),
        ),
        migrations.AlterField(
            model_name="containerforecastsummary",
            name="needs_planning_attention",
            field=models.BooleanField(
                default=False, help_text="Approaching threshold without a plan (TIER 3)"
            ),
        ),
        migrations.AlterField(
            model_name="containerforecastsummary",
            name="original_harvest_date",
            field=models.DateField(
                blank=True,
                help_text="Original harvest date from scenario ProjectionDay",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="containerforecastsummary",
            name="projected_harvest_date",
            field=models.DateField(
                blank=True,
                help_text="First date projected weight crosses harvest threshold",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="containerforecastsummary",
            name="projected_transfer_date",
            field=models.DateField(
                blank=True,
                help_text="First date projected weight crosses transfer threshold",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="liveforwardprojection",
            name="batch",
            field=models.ForeignKey(
                help_text="Batch (denormalized from assignment)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_projections",
                to="batch.batch",
            ),
        ),
        migrations.AlterField(
            model_name="liveforwardprojection",
            name="container",
            field=models.ForeignKey(
                help_text="Container (denormalized from assignment)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="live_projections",
                to="infrastructure.container",
            ),
        ),
        migrations.AlterField(
            model_name="liveforwardprojection",
            name="day_number",
            field=models.PositiveIntegerField(
                help_text="Day number in batch lifecycle (1-based from start_date)"
            ),
        ),
        migrations.AlterField(
            model_name="liveforwardprojection",
            name="temp_profile_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of the TemperatureProfile used as baseline",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="liveforwardprojection",
            name="temp_profile_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Name of TemperatureProfile (denormalized for display)",
                max_length=255,
            ),
        ),
    ]
