# Generated by Django 4.2.11 on 2026-02-18 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0047_actualdailyassignmentstate_planned_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchtransferworkflow",
            name="is_dynamic_execution",
            field=models.BooleanField(
                default=False,
                help_text="When true, actions are created during execution time by ship crew instead of pre-defined during planning.",
            ),
        ),
        migrations.AddField(
            model_name="historicalbatchtransferworkflow",
            name="is_dynamic_execution",
            field=models.BooleanField(
                default=False,
                help_text="When true, actions are created during execution time by ship crew instead of pre-defined during planning.",
            ),
        ),
    ]
