# Generated by Django 4.2.11 on 2026-02-26 14:38

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0010_areagroup_container_hierarchy_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batch", "0048_batchtransferworkflow_is_dynamic_execution_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchMixEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mixed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "container",
                    models.ForeignKey(
                        help_text="Container where mixing physically occurred.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mix_events",
                        to="infrastructure.container",
                    ),
                ),
                (
                    "mixed_batch",
                    models.ForeignKey(
                        help_text="Resulting mixed batch created/updated by this mix event.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mix_events",
                        to="batch.batch",
                    ),
                ),
                (
                    "workflow_action",
                    models.ForeignKey(
                        blank=True,
                        help_text="Transfer action that triggered this mix, when applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mix_events",
                        to="batch.transferaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-mixed_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBatchMixEventComponent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "population_count",
                    models.PositiveIntegerField(
                        help_text="Fish count contributed from this source.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "biomass_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Biomass contributed from this source in kilograms.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage share of total mixed population at event time.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "is_transferred_in",
                    models.BooleanField(
                        default=False,
                        help_text="True when this component came from the action's transferred fish.",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mix_event",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batchmixevent",
                    ),
                ),
                (
                    "source_assignment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Assignment contributing fish to this mix event.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batchcontainerassignment",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Batch identity for this component (snapshot for analytics).",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batch",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical batch mix event component",
                "verbose_name_plural": "historical batch mix event components",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBatchMixEvent",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("mixed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Container where mixing physically occurred.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="infrastructure.container",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mixed_batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Resulting mixed batch created/updated by this mix event.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batch",
                    ),
                ),
                (
                    "workflow_action",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Transfer action that triggered this mix, when applicable.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.transferaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical batch mix event",
                "verbose_name_plural": "historical batch mix events",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="BatchMixEventComponent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "population_count",
                    models.PositiveIntegerField(
                        help_text="Fish count contributed from this source.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "biomass_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Biomass contributed from this source in kilograms.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Percentage share of total mixed population at event time.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                (
                    "is_transferred_in",
                    models.BooleanField(
                        default=False,
                        help_text="True when this component came from the action's transferred fish.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mix_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="components",
                        to="batch.batchmixevent",
                    ),
                ),
                (
                    "source_assignment",
                    models.ForeignKey(
                        help_text="Assignment contributing fish to this mix event.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mix_event_components",
                        to="batch.batchcontainerassignment",
                    ),
                ),
                (
                    "source_batch",
                    models.ForeignKey(
                        help_text="Batch identity for this component (snapshot for analytics).",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mix_event_contributions",
                        to="batch.batch",
                    ),
                ),
            ],
            options={
                "ordering": ["-population_count", "-id"],
                "indexes": [
                    models.Index(
                        fields=["mix_event", "source_batch"],
                        name="batch_batch_mix_eve_9c67ba_idx",
                    ),
                    models.Index(
                        fields=["source_assignment"],
                        name="batch_batch_source__c06fcd_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="batchmixevent",
            index=models.Index(
                fields=["mixed_batch", "mixed_at"],
                name="batch_batch_mixed_b_d8f8a8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="batchmixevent",
            index=models.Index(
                fields=["container", "mixed_at"], name="batch_batch_contain_ac25e1_idx"
            ),
        ),
    ]
