# Generated by Django 4.2.11 on 2026-03-04 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0010_areagroup_container_hierarchy_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batch", "0049_batchmixevent_historicalbatchmixeventcomponent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchtransferworkflow",
            name="dynamic_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of explicit dynamic workflow completion.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="batchtransferworkflow",
            name="dynamic_completed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who explicitly completed a dynamic workflow.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dynamically_completed_transfer_workflows",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="batchtransferworkflow",
            name="dynamic_route_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECT_STATION_TO_VESSEL", "Direct Station to Vessel"),
                    ("VIA_TRUCK_TO_VESSEL", "Via Truck to Vessel"),
                ],
                help_text="Dynamic route pattern for station-to-sea workflows. Required when is_dynamic_execution is true.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="batchtransferworkflow",
            name="estimated_total_biomass_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional operator estimate of total biomass to move.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="batchtransferworkflow",
            name="estimated_total_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional operator estimate of total count to move.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbatchtransferworkflow",
            name="dynamic_completed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp of explicit dynamic workflow completion.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbatchtransferworkflow",
            name="dynamic_completed_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="User who explicitly completed a dynamic workflow.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbatchtransferworkflow",
            name="dynamic_route_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DIRECT_STATION_TO_VESSEL", "Direct Station to Vessel"),
                    ("VIA_TRUCK_TO_VESSEL", "Via Truck to Vessel"),
                ],
                help_text="Dynamic route pattern for station-to-sea workflows. Required when is_dynamic_execution is true.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbatchtransferworkflow",
            name="estimated_total_biomass_kg",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional operator estimate of total biomass to move.",
                max_digits=12,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalbatchtransferworkflow",
            name="estimated_total_count",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Optional operator estimate of total count to move.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaltransferaction",
            name="created_via",
            field=models.CharField(
                choices=[("PLANNED", "Planned"), ("DYNAMIC_LIVE", "Dynamic Live")],
                default="PLANNED",
                help_text="How this action was created (planned vs live dynamic start).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="historicaltransferaction",
            name="dest_container",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Destination container for dynamic live handoffs.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="infrastructure.container",
            ),
        ),
        migrations.AddField(
            model_name="historicaltransferaction",
            name="executed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="High-resolution execution timestamp for operational ordering.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicaltransferaction",
            name="leg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STATION_TO_VESSEL", "Station to Vessel"),
                    ("STATION_TO_TRUCK", "Station to Truck"),
                    ("TRUCK_TO_VESSEL", "Truck to Vessel"),
                    ("VESSEL_TO_RING", "Vessel to Ring"),
                ],
                help_text="Explicit transport leg type for dynamic handoffs.",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transferaction",
            name="created_via",
            field=models.CharField(
                choices=[("PLANNED", "Planned"), ("DYNAMIC_LIVE", "Dynamic Live")],
                default="PLANNED",
                help_text="How this action was created (planned vs live dynamic start).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="transferaction",
            name="dest_container",
            field=models.ForeignKey(
                blank=True,
                help_text="Destination container for dynamic live handoffs.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfer_actions_as_dest_container",
                to="infrastructure.container",
            ),
        ),
        migrations.AddField(
            model_name="transferaction",
            name="executed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="High-resolution execution timestamp for operational ordering.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="transferaction",
            name="leg_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STATION_TO_VESSEL", "Station to Vessel"),
                    ("STATION_TO_TRUCK", "Station to Truck"),
                    ("TRUCK_TO_VESSEL", "Truck to Vessel"),
                    ("VESSEL_TO_RING", "Vessel to Ring"),
                ],
                help_text="Explicit transport leg type for dynamic handoffs.",
                max_length=32,
                null=True,
            ),
        ),
    ]
