# Generated by Django 4.2.11 on 2025-12-01 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("batch", "0040_migrate_pinned_scenario_to_run"),
        ("scenario", "0011_migrate_projections_to_runs"),
        (
            "infrastructure",
            "0008_alter_area_options_alter_containertype_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalPlannedActivity",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("VACCINATION", "Vaccination"),
                            ("TREATMENT", "Treatment/Health Intervention"),
                            ("CULL", "Culling"),
                            ("SALE", "Sale/Harvest"),
                            ("FEED_CHANGE", "Feed Strategy Change"),
                            ("TRANSFER", "Transfer"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SAMPLING", "Sampling"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of operational activity",
                        max_length=50,
                    ),
                ),
                ("due_date", models.DateField(help_text="Planned execution date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the activity",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Free-text notes for context", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when activity was completed",
                        null=True,
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Batch this activity is planned for",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batch",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who marked activity as completed",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Target container (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="infrastructure.container",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="User who created this activity",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Scenario this activity belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="scenario.scenario",
                    ),
                ),
                (
                    "transfer_workflow",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Spawned Transfer Workflow (for TRANSFER activities)",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batchtransferworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Planned Activity",
                "verbose_name_plural": "historical Planned Activities",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ActivityTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Template name (e.g., 'Standard Atlantic Salmon Lifecycle')",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Template description", null=True
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("VACCINATION", "Vaccination"),
                            ("TREATMENT", "Treatment/Health Intervention"),
                            ("CULL", "Culling"),
                            ("SALE", "Sale/Harvest"),
                            ("FEED_CHANGE", "Feed Strategy Change"),
                            ("TRANSFER", "Transfer"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SAMPLING", "Sampling"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of activity to generate",
                        max_length=50,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("DAY_OFFSET", "Day Offset"),
                            ("WEIGHT_THRESHOLD", "Weight Threshold"),
                            ("STAGE_TRANSITION", "Stage Transition"),
                        ],
                        help_text="When to create the activity",
                        max_length=20,
                    ),
                ),
                (
                    "day_offset",
                    models.IntegerField(
                        blank=True,
                        help_text="Days after batch creation (for DAY_OFFSET trigger)",
                        null=True,
                    ),
                ),
                (
                    "weight_threshold_g",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Average weight threshold (for WEIGHT_THRESHOLD trigger)",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "notes_template",
                    models.TextField(
                        blank=True, help_text="Template for activity notes", null=True
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether template is active"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "target_lifecycle_stage",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target stage for STAGE_TRANSITION trigger",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="target_templates",
                        to="batch.lifecyclestage",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Template",
                "verbose_name_plural": "Activity Templates",
                "db_table": "planning_activitytemplate",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PlannedActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("VACCINATION", "Vaccination"),
                            ("TREATMENT", "Treatment/Health Intervention"),
                            ("CULL", "Culling"),
                            ("SALE", "Sale/Harvest"),
                            ("FEED_CHANGE", "Feed Strategy Change"),
                            ("TRANSFER", "Transfer"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SAMPLING", "Sampling"),
                            ("OTHER", "Other"),
                        ],
                        help_text="Type of operational activity",
                        max_length=50,
                    ),
                ),
                ("due_date", models.DateField(help_text="Planned execution date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("OVERDUE", "Overdue"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the activity",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Free-text notes for context", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when activity was completed",
                        null=True,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Batch this activity is planned for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_activities",
                        to="batch.batch",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who marked activity as completed",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_planned_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        help_text="Target container (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastructure.container",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this activity",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_planned_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scenario",
                    models.ForeignKey(
                        help_text="Scenario this activity belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_activities",
                        to="scenario.scenario",
                    ),
                ),
                (
                    "transfer_workflow",
                    models.ForeignKey(
                        blank=True,
                        help_text="Spawned Transfer Workflow (for TRANSFER activities)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="batch.batchtransferworkflow",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planned Activity",
                "verbose_name_plural": "Planned Activities",
                "db_table": "planning_plannedactivity",
                "ordering": ["due_date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["scenario", "due_date"], name="idx_pa_scenario_due_date"
                    ),
                    models.Index(
                        fields=["batch", "status"], name="idx_pa_batch_status"
                    ),
                    models.Index(
                        fields=["activity_type", "status"], name="idx_pa_type_status"
                    ),
                ],
            },
        ),
    ]
