# Generated by Django 4.2.11 on 2025-12-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalplannedactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                help_text="Current status of the activity",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="plannedactivity",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("IN_PROGRESS", "In Progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                help_text="Current status of the activity",
                max_length=20,
            ),
        ),
    ]
