# Generated by Django 4.2.11 on 2025-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0002_remove_overdue_status_choice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitytemplate",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("VACCINATION", "Vaccination"),
                    ("TREATMENT", "Treatment/Health Intervention"),
                    ("CULL", "Culling"),
                    ("HARVEST", "Harvest"),
                    ("SALE", "Sale/Commercial Handoff"),
                    ("FEED_CHANGE", "Feed Strategy Change"),
                    ("TRANSFER", "Transfer"),
                    ("MAINTENANCE", "Maintenance"),
                    ("SAMPLING", "Sampling"),
                    ("OTHER", "Other"),
                ],
                help_text="Type of activity to generate",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="historicalplannedactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("VACCINATION", "Vaccination"),
                    ("TREATMENT", "Treatment/Health Intervention"),
                    ("CULL", "Culling"),
                    ("HARVEST", "Harvest"),
                    ("SALE", "Sale/Commercial Handoff"),
                    ("FEED_CHANGE", "Feed Strategy Change"),
                    ("TRANSFER", "Transfer"),
                    ("MAINTENANCE", "Maintenance"),
                    ("SAMPLING", "Sampling"),
                    ("OTHER", "Other"),
                ],
                help_text="Type of operational activity",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="plannedactivity",
            name="activity_type",
            field=models.CharField(
                choices=[
                    ("VACCINATION", "Vaccination"),
                    ("TREATMENT", "Treatment/Health Intervention"),
                    ("CULL", "Culling"),
                    ("HARVEST", "Harvest"),
                    ("SALE", "Sale/Commercial Handoff"),
                    ("FEED_CHANGE", "Feed Strategy Change"),
                    ("TRANSFER", "Transfer"),
                    ("MAINTENANCE", "Maintenance"),
                    ("SAMPLING", "Sampling"),
                    ("OTHER", "Other"),
                ],
                help_text="Type of operational activity",
                max_length=50,
            ),
        ),
    ]
