# Generated by Django 4.2.11 on 2025-03-12 13:59

from django.db import migrations


class Migration(migrations.Migration):
    """
    Migration to create TimescaleDB hypertables for time-series data models.
    
    Following TimescaleDB requirements, this migration:    
    1. Creates unique constraints that include time columns (needed for hypertable compatibility)
    2. Creates the hypertables for EnvironmentalReading and WeatherData tables
    """

    dependencies = [
        ("environmental", "0001_initial"),
    ]

    operations = [
        # 1. Add unique constraints with time columns for EnvironmentalReading
        migrations.RunSQL(
            sql='''
            -- First drop the primary key constraint (keeping the id column)
            ALTER TABLE environmental_environmentalreading 
            DROP CONSTRAINT environmental_environmentalreading_pkey;
            
            -- Create a composite primary key including the time column
            ALTER TABLE environmental_environmentalreading
            ADD CONSTRAINT environmental_environmentalreading_pkey
            PRIMARY KEY (id, reading_time);
            ''',
            reverse_sql='''
            -- Restore original primary key
            ALTER TABLE environmental_environmentalreading
            DROP CONSTRAINT environmental_environmentalreading_pkey;
            
            ALTER TABLE environmental_environmentalreading
            ADD CONSTRAINT environmental_environmentalreading_pkey
            PRIMARY KEY (id);
            '''
        ),
        
        # 2. Add unique constraints with time columns for WeatherData
        migrations.RunSQL(
            sql='''
            -- First drop the primary key constraint (keeping the id column)
            ALTER TABLE environmental_weatherdata 
            DROP CONSTRAINT environmental_weatherdata_pkey;
            
            -- Create a composite primary key including the time column
            ALTER TABLE environmental_weatherdata
            ADD CONSTRAINT environmental_weatherdata_pkey
            PRIMARY KEY (id, timestamp);
            ''',
            reverse_sql='''
            -- Restore original primary key
            ALTER TABLE environmental_weatherdata
            DROP CONSTRAINT environmental_weatherdata_pkey;
            
            ALTER TABLE environmental_weatherdata
            ADD CONSTRAINT environmental_weatherdata_pkey
            PRIMARY KEY (id);
            '''
        ),
        
        # 3. Create hypertable for EnvironmentalReading
        migrations.RunSQL(
            sql='''
            SELECT create_hypertable('environmental_environmentalreading', 'reading_time',
                                    if_not_exists => TRUE,
                                    migrate_data => TRUE,
                                    chunk_time_interval => INTERVAL '7 days');
            ''',
            reverse_sql='''
            -- No direct way to convert hypertable back to regular table
            -- In production, you would need to backup data, drop the table, and recreate it
            '''
        ),
        
        # 4. Create hypertable for WeatherData
        migrations.RunSQL(
            sql='''
            SELECT create_hypertable('environmental_weatherdata', 'timestamp',
                                    if_not_exists => TRUE,
                                    migrate_data => TRUE,
                                    chunk_time_interval => INTERVAL '7 days');
            ''',
            reverse_sql='''
            -- No direct way to convert hypertable back to regular table
            -- In production, you would need to backup data, drop the table, and recreate it
            '''
        ),
    ]
