# Generated by Django 4.2.11 on 2025-04-28 10:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('environmental', '0007_fix_sqlite_compatibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
