# Generated by Django 4.2.11 on 2025-09-02 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("batch", "0016_historicalbatch"),
        ("environmental", "0008_alter_weatherdata_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="environmentalreading",
            name="batch_container_assignment",
            field=models.ForeignKey(
                blank=True,
                help_text="Direct link to the batch-container assignment for precise salmon CV tracking",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="environmental_readings",
                to="batch.batchcontainerassignment",
            ),
        ),
        migrations.AddIndex(
            model_name="environmentalreading",
            index=models.Index(
                fields=["batch_container_assignment", "parameter", "reading_time"],
                name="environment_batch_c_343740_idx",
            ),
        ),
    ]
