# Generated by Django 4.2.11 on 2025-09-02 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0007_add_container_history"),
        ("environmental", "0010_populate_batch_container_assignment_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="environmentalreading",
            name="container",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="environmental_readings",
                to="infrastructure.container",
            ),
        ),
    ]
