# Generated by Django 4.2.11 on 2025-10-11 11:07

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0008_alter_area_options_alter_containertype_options_and_more",
        ),
        ("batch", "0022_add_history_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("environmental", "0011_update_container_fk_constraint"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalStageTransitionEnvironmental",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Water temperature in °C",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "oxygen",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Dissolved oxygen in mg/L",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "salinity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Salinity in ppt",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "ph",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="pH level",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "additional_parameters",
                    models.JSONField(
                        blank=True,
                        help_text="Additional environmental parameters",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "batch_transfer",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="batch.batchtransfer",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical stage transition environmental",
                "verbose_name_plural": "historical stage transition environmentals",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPhotoperiodData",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                (
                    "day_length_hours",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Day length in hours (0-24)",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("24")),
                        ],
                    ),
                ),
                (
                    "light_intensity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Light intensity in lux",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "is_interpolated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this data point was interpolated rather than measured",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="infrastructure.area",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical photoperiod data",
                "verbose_name_plural": "historical photoperiod datas",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalEnvironmentalParameter",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("unit", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum acceptable value for this parameter",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum acceptable value for this parameter",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "optimal_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum optimal value for this parameter",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "optimal_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum optimal value for this parameter",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical environmental parameter",
                "verbose_name_plural": "historical environmental parameters",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
