# Generated by Django 4.2.11 on 2025-06-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("broodstock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="breedingplan",
            name="breeder_instructions",
            field=models.TextField(
                blank=True,
                help_text="Clear instructions for breeders on execution of the breeding plan",
            ),
        ),
        migrations.AddField(
            model_name="breedingplan",
            name="geneticist_notes",
            field=models.TextField(
                blank=True,
                help_text="Technical notes from geneticist about breeding priorities and trait selection",
            ),
        ),
    ]
