# Generated by Django 4.2.11 on 2025-06-12 14:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("broodstock", "0002_add_communication_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fishmovement",
            name="movement_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Date and time of movement",
            ),
        ),
        migrations.AlterField(
            model_name="historicalfishmovement",
            name="movement_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Date and time of movement",
            ),
        ),
    ]
