name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Drop test database if it exists
      run: |
        export PGPASSWORD=postgres
        psql -h localhost -U postgres -c "DROP DATABASE IF EXISTS test_aquamind;" || true
    
    - name: Run migrations with --noinput flag
      run: |
        python manage.py migrate --settings=test_settings --noinput
      env:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
    
    - name: Run tests for implemented features only
      run: |
        # Only run tests for implemented features
        # As we complete more features from the implementation plan, we'll add their tests here
        python manage.py test apps.environmental.tests.test_api.test_weather_api --settings=test_settings --noinput
      env:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
