name: Backend Docker Build

on:
  push:
    branches: [ main, develop, test ]
    paths:
      - 'Dockerfile.dev'
      - 'docker-compose.yml'
      - 'requirements.txt'
      - 'aquamind/**'
      - 'apps/**'
      - 'scripts/**'
  pull_request:
    branches: [ main, develop, test ]
    paths:
      - 'Dockerfile.dev'
      - 'docker-compose.yml'
      - 'requirements.txt'
      - 'aquamind/**'
      - 'apps/**'
      - 'scripts/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}/backend
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.dev
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v1
      with:
        subject-name: ghcr.io/${{ github.repository }}/backend
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true
