name: OpenAPI Specification Sync Check

on:
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'apps/**/api/**/*.py'
      - 'apps/**/viewsets/**/*.py'
      - 'apps/**/serializers/**/*.py'
      - 'apps/**/routers/**/*.py'
      - 'aquamind/api/**/*.py'
      - 'aquamind/utils/openapi_utils.py'
      - 'api/openapi.yaml'

jobs:
  check-openapi-sync:
    name: Verify OpenAPI Spec Matches Code
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate fresh OpenAPI spec
      run: |
        # Generate spec to a temporary file
        python manage.py spectacular --file /tmp/fresh-openapi.yaml --settings=aquamind.settings_ci
        echo "✅ Fresh OpenAPI spec generated"
    
    - name: Compare with committed spec
      id: compare
      run: |
        if ! diff -q /tmp/fresh-openapi.yaml api/openapi.yaml > /dev/null; then
          echo "::error::OpenAPI specification is out of sync with code!"
          echo "::error::The committed spec doesn't match what would be generated from the current code."
          echo "❌ Spec mismatch detected"
          echo "is_sync=false" >> $GITHUB_OUTPUT
          
          # Create a diff for the summary
          diff -u api/openapi.yaml /tmp/fresh-openapi.yaml > /tmp/spec-diff.txt || true
          
          # Count the number of different lines
          DIFF_LINES=$(grep -c "^[+-]" /tmp/spec-diff.txt || echo "0")
          echo "diff_lines=$DIFF_LINES" >> $GITHUB_OUTPUT
        else
          echo "✅ OpenAPI spec is in sync with code"
          echo "is_sync=true" >> $GITHUB_OUTPUT
          echo "diff_lines=0" >> $GITHUB_OUTPUT
        fi
    
    - name: Generate summary of differences
      if: steps.compare.outputs.is_sync == 'false'
      run: |
        echo "## ❌ OpenAPI Specification Mismatch" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The OpenAPI specification is out of sync with the code." >> $GITHUB_STEP_SUMMARY
        echo "There are approximately ${{ steps.compare.outputs.diff_lines }} lines that differ." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### How to fix this" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "1. Run `python manage.py spectacular --file api/openapi.yaml` locally" >> $GITHUB_STEP_SUMMARY
        echo "2. Commit the updated spec file" >> $GITHUB_STEP_SUMMARY
        echo "3. Push the changes to your branch" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Alternatively, you can use the provided script:" >> $GITHUB_STEP_SUMMARY
        echo "```bash" >> $GITHUB_STEP_SUMMARY
        echo "./scripts/regenerate_openapi.sh" >> $GITHUB_STEP_SUMMARY
        echo "```" >> $GITHUB_STEP_SUMMARY
    
    - name: Fail if specs don't match
      if: steps.compare.outputs.is_sync == 'false'
      run: |
        echo "::error::OpenAPI specification is out of sync with code. Please regenerate the spec using 'python manage.py spectacular --file api/openapi.yaml' or './scripts/regenerate_openapi.sh'"
        exit 1
