# Generated by Django 4.2.11 on 2025-11-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExternalIdMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        help_text="External system identifier, e.g. 'FishTalk'.",
                        max_length=32,
                    ),
                ),
                (
                    "source_model",
                    models.CharField(
                        help_text="Source table or entity name.", max_length=64
                    ),
                ),
                (
                    "source_identifier",
                    models.CharField(
                        help_text="Primary identifier in the source system.",
                        max_length=128,
                    ),
                ),
                (
                    "target_app_label",
                    models.CharField(
                        help_text="Target Django app label (apps.batch, apps.inventory, etc.).",
                        max_length=64,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="Target Django model name.", max_length=64
                    ),
                ),
                (
                    "target_object_id",
                    models.BigIntegerField(help_text="Primary key in AquaMind."),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional JSON payload for extra mapping info (dates, notes, etc.).",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "External ID Map",
                "verbose_name_plural": "External ID Maps",
                "indexes": [
                    models.Index(
                        fields=["source_system", "source_model"],
                        name="migration_s_source__6a4e0a_idx",
                    ),
                    models.Index(
                        fields=["target_app_label", "target_model", "target_object_id"],
                        name="migration_s_target__b24f64_idx",
                    ),
                ],
                "unique_together": {
                    ("source_system", "source_model", "source_identifier")
                },
            },
        ),
    ]
